// ignore_for_file: avoid_classes_with_only_static_members

import 'package:health_gauge/utils/gloabals.dart';

import 'string_localization.dart';

/// Added by: Akhil
/// Added on: May/28/2020
/// This class contains all the Strings which are used in app in English Language

class EnglishLocalization {
  static Map<String, String> getLocalization = {
    StringLocalization.appName: 'Health Gauge',
    StringLocalization.dashBoardName: 'Follow Your Heart',
    StringLocalization.cnctnScreen: 'Connection',
    StringLocalization.settingScreen: 'Settings',
    StringLocalization.targetScreen: 'Steps Target',
    StringLocalization.tagHistory: 'Tag History',
    StringLocalization.sleeptargetScreen: 'Sleep Target',
    StringLocalization.btnTitle: 'Button Title',
    StringLocalization.btnTag: 'ADD TAG',
    StringLocalization.btnTagU: 'UPDATE TAG',
    StringLocalization.displayOne: 'Display One',
    StringLocalization.tagScreen: 'Tag',
    StringLocalization.tagScreenSlctn: 'Tag Selection',
    StringLocalization.headline: 'Headline',
    StringLocalization.subHeadline: 'SubHead',
    StringLocalization.title: 'Title',
    StringLocalization.subTitle: 'Sub Title',
    StringLocalization.body2: 'Body2',
    StringLocalization.body1: 'Body1',
    StringLocalization.small: 'Small',
    StringLocalization.caption: 'Caption',
    StringLocalization.appbarMgmt: 'Device Management',
    StringLocalization.monitor: 'CONNECT DEVICE',
    StringLocalization.timeFormat: 'Time Format',
    StringLocalization.timeF: '24h',
    StringLocalization.timeFo: '12h',
    StringLocalization.reset: 'Reset',
    StringLocalization.resetWatch: 'Smartwatch Factory Reset',
    StringLocalization.hrMonitor: 'Hourly HR Monitor',
    StringLocalization.bScreen: 'Lift the wrist brighten screen',
    StringLocalization.dNd: 'Do Not Disturb',
    StringLocalization.firmUpdate: 'Firmware Updates',
    StringLocalization.noInternet: 'Oops!',
    StringLocalization.enableInternet:
        'Seems like you are not connected to internet. Enable your data connection',
    StringLocalization.retry: 'Retry',
    StringLocalization.cncl: 'Cancel',
    StringLocalization.mileage: 'Mile',
    StringLocalization.kCal: 'Kcal',
    StringLocalization.comp: 'Completion',
    StringLocalization.hintForUserId: 'User ID',
    StringLocalization.hintForPassword: 'Password',
    StringLocalization.hintForNewPassword: 'New Password',
    StringLocalization.loginBtn: 'Login',
    StringLocalization.type: 'Type',
    StringLocalization.stps: 'Steps',
    StringLocalization.value: 'Value',
    StringLocalization.time: 'Time',
    StringLocalization.date: 'Date',
    StringLocalization.notes: 'Notes',
    StringLocalization.day: 'Day',
    StringLocalization.week: 'Week',
    StringLocalization.month: 'Month',
    StringLocalization.timeH: 'Time',
    StringLocalization.typeH: 'Type',
    StringLocalization.valueH: 'Value',
    StringLocalization.noteH: 'Note',
    StringLocalization.weekH: 'This Week',
    StringLocalization.lastH: 'Last Week',
    StringLocalization.skipBtn: 'Skip',
    StringLocalization.btnForgotPassword: 'Forgot password?',
    StringLocalization.btnForgotUserId: 'Forgot UserId?',
    StringLocalization.next: 'Next',
    StringLocalization.dontHaveAnAccount: 'Don\'t have an account?',
    StringLocalization.btnSignUp: 'Sign Up',
    StringLocalization.btnConnect: 'Connect',
    StringLocalization.btnDisConnect: 'Disconnect',
    StringLocalization.emptyUserId: 'Enter User ID',
    StringLocalization.emptyPassword: 'Enter Password',
    StringLocalization.emptyNewPassword: 'Enter New Password',
    StringLocalization.btnLogout: 'Logout',
    StringLocalization.hintForEmail: 'Email',
    StringLocalization.emptyEmail: 'Enter Email',
    StringLocalization.enterValidEmail: 'Enter Valid Email',
    StringLocalization.hintForFirstName: 'First Name',
    StringLocalization.emptyFirstName: 'Enter First Name',
    StringLocalization.hintForLastName: 'Last Name',
    StringLocalization.emptyLastName: 'Enter Last Name',
    StringLocalization.hintForBirthDate: 'Date of Birth',
    StringLocalization.emptyBirthDate: 'Enter Birth Date',
    StringLocalization.hintForPhone: 'Phone Number',
    StringLocalization.emptyPhone: 'Enter Phone Number',
    StringLocalization.enterValidPhone: 'Enter Valid Phone Number',
    StringLocalization.confirmPasswordDoesntMatch: 'Confirm Password Doesn\'t Match',
    StringLocalization.hintForConfirmPassword: 'Confirm Password',
    StringLocalization.emptyConfirmPassword: 'Enter Confirm Password',
    StringLocalization.passwordMismatch: 'Password must match',
    StringLocalization.passwordInvalid: 'Invalid Password',
    StringLocalization.termsAndConditions: 'Terms And Conditions',
    StringLocalization.readMore: 'Read More',
    StringLocalization.agreeTermsAndCondition: 'Please Accept Terms And Conditions.',
    StringLocalization.save: 'Save',
    StringLocalization.profile: 'Profile',
    StringLocalization.pleaseLoginFirstToUseThisFeature: 'Please Login first to use this feature?',
    StringLocalization.cancel: 'Cancel',
    StringLocalization.ok: 'Ok',
    StringLocalization.deviceBattery: 'Device Battery',
    StringLocalization.bp: 'BP',
    StringLocalization.bloodPressure: 'Blood Pressure',
    StringLocalization.bloodOxygen: 'Blood Oxygen',
    StringLocalization.activeCalorieBurn: 'Active Calorie Burn',
    StringLocalization.restingCalorieBurn: 'Resting Calorie Burn',
    StringLocalization.oxygen: 'Oxygen',
    StringLocalization.offLineEcgSbp: '0/0',
    StringLocalization.heartRate: 'Heart Rate',
    StringLocalization.hrv: 'HRV',
    StringLocalization.health: 'Health',
    StringLocalization.symptoms: 'Symptoms',
    StringLocalization.complete: 'Complete',
    StringLocalization.steps: 'Steps',
    StringLocalization.calories: 'Calories',
    StringLocalization.kml: 'kcal',
    StringLocalization.zeroKml: 'kml',
    StringLocalization.distance: 'Distance',
    StringLocalization.km: 'Km',
    StringLocalization.zeroKm: '0 km',
    StringLocalization.activity: 'Activity',
    StringLocalization.sleepS: 'Sleep',
    StringLocalization.sleepHour: 'Sleep Hour',
    StringLocalization.hour: 'Hour',
    StringLocalization.sleep: 'Sleep',
    StringLocalization.disconnect: 'Disconnect!',
    StringLocalization.areYouSureWantToDisconnect: 'Are you sure want to disconnect',
    StringLocalization.connectedDevice: 'Connected Device',
    StringLocalization.connected: 'Connected',
    StringLocalization.disconnected: 'Disconnected',
    StringLocalization.andConnect: 'and connect',
    StringLocalization.gender: 'Sex',
    StringLocalization.male: 'M',
    StringLocalization.female: 'F',
    StringLocalization.others: 'O',
    StringLocalization.unit: 'Unit',
    StringLocalization.metric: 'Metric',
    StringLocalization.imperial: 'Imperial',
    StringLocalization.dateOfBirth: 'Date of Birth',
    StringLocalization.selectBirthDate: 'Select Birth Date',
    StringLocalization.height: 'Height',
    StringLocalization.confirm: 'Confirm',
    StringLocalization.feet: 'Feet',
    StringLocalization.inch: 'Inch',
    StringLocalization.skinPhotoType: 'Skin Phototype',
    StringLocalization.width: 'Width',
    StringLocalization.lb: 'lb',
    StringLocalization.measurement: 'Measurement',
    StringLocalization.startMeasurement: 'Start Measurement',
    StringLocalization.setUnit: 'Unit Settings',
    StringLocalization.training: 'Training',
    StringLocalization.hrBPM: 'HR (bpm)',
    StringLocalization.bpMmHg: 'BP',
    StringLocalization.bplegend:
        'Data presented is for information, and not considered as medical data.',
    StringLocalization.countDown: 'Countdown: ',
    StringLocalization.ecg: 'ECG',
    StringLocalization.ppg: 'PPG',
    StringLocalization.calibration: 'Calibration',
    StringLocalization.hr: 'Heart Rate',
    StringLocalization.sbd: 'Systolic BP',
    StringLocalization.dbp: 'Diastolic BP',
    StringLocalization.shortDescription: 'Please enter readings from your  oscillometric device.',
    StringLocalization.add: 'ADD',
    StringLocalization.addToGraph: 'ADD TO GRAPH',
    StringLocalization.measurementHistory: 'AI PrecisionPulse',
    StringLocalization.today: 'Today',
    StringLocalization.yesterday: 'Yesterday',
    StringLocalization.tomorrow: 'Tomorrow',
    StringLocalization.stopMeasurement: 'Stop Measurement',
    StringLocalization.edit: 'Edit',
    StringLocalization.camera: 'Take Picture',
    StringLocalization.gallery: 'Choose from phone',
    StringLocalization.remove: 'Remove',
    StringLocalization.min: 'Min',
    StringLocalization.max: 'Max',
    StringLocalization.enterMin: 'Enter Min',
    StringLocalization.minMustBeSmallerThenMax: 'Min Range must be less than Max Range',
    StringLocalization.enterMax: 'Enter Max',
    StringLocalization.minMustBeSmallerThenMin: 'Invalid value',
    StringLocalization.label: 'Tag Label',
    StringLocalization.enterLabel: 'Enter Tag Label',
    StringLocalization.defaultValue: 'Enter Value',
    StringLocalization.enterBetween: 'Enter between',
    StringLocalization.digit: 'Digit',
    StringLocalization.enterDigit: 'Enter Digit',
    StringLocalization.centimetre: 'Centimetre',
    StringLocalization.kg: 'kg',
    StringLocalization.weight: 'Weight',
    StringLocalization.updatedSuccessfully: 'Updated Successfully',
    StringLocalization.failToUpdate: 'Fail to update',
    StringLocalization.sleepHistoryTitle: 'Sleep',
    StringLocalization.chooseYourStepTarget: 'Choose your step target',
    StringLocalization.stepSuggestion: 'Suggestion: 8000 ~ 10000 steps each day',
    StringLocalization.chooseSleepTarget: 'Choose your sleep target',
    StringLocalization.sleepSuggestion: 'Suggestion: adults sleep 7 - 9 hours a day',
    StringLocalization.noDataFound: 'No Data Found.',
    StringLocalization.stayUp: 'Stay Up',
    StringLocalization.light: 'Light',
    StringLocalization.deep: 'Deep',
    StringLocalization.commingSoon: 'Coming Soon',
    StringLocalization.target: 'Goals',
    StringLocalization.minute: 'Minute',
    StringLocalization.privacyPolicy: 'Privacy Policy',
    StringLocalization.tagLabelEditor: 'Tag Label Editor',
    StringLocalization.addTagTitle: 'Add New Tag',
    StringLocalization.update: 'Update',
    StringLocalization.selectTag: 'Selected Tag',
    StringLocalization.range: 'Range',
    StringLocalization.minimum: 'Minimum',
    StringLocalization.maximum: 'Maximum',
    StringLocalization.defaultValueTag: 'Default Value: ',
    StringLocalization.precision: 'Precision',
    StringLocalization.tag: 'Tag',
    StringLocalization.tagValue: 'Value: ',
    StringLocalization.change: 'Change',
    StringLocalization.addNote: 'Add Tag',
    StringLocalization.updateNote: 'Update Tag',
    StringLocalization.enterUnit: 'Enter Unit',
    StringLocalization.stress: 'Stress',
    StringLocalization.number: 'Number',
    StringLocalization.fatigue: 'Fatigue',
    StringLocalization.bloodGlucose: 'Blood Glucose',
    StringLocalization.glucoseCalibrationTag: 'P5.0 Glucose Calibration',
    StringLocalization.exercise: 'Exercise',
    StringLocalization.bodyTemperature: 'Temperature',
    StringLocalization.celsius: 'Celsius',
    StringLocalization.breathing: 'Breathing',
    StringLocalization.deviceManagement: 'Device Settings',
    StringLocalization.hourlyHrMonitor: 'Hourly HR Monitor',
    StringLocalization.hourlyBPMonitor: 'Hourly BP Monitor',
    StringLocalization.liftTheWristBrighten: 'Lift The Wrist To Brighten Screen',
    StringLocalization.doNotDisturb: 'Do Not Disturb',
    StringLocalization.twelve: '12h',
    StringLocalization.twentyFour: '24h',
    StringLocalization.wearType: 'Wearing Method',
    StringLocalization.leftHand: 'Left',
    StringLocalization.rightHand: 'Right',
    StringLocalization.graph: 'Graph',
    StringLocalization.selectItem: 'Select Item',
    StringLocalization.somethingWentWrong: 'Something Went Wrong',
    StringLocalization.oops: 'Opps!',
    StringLocalization.unknown: 'unknown',
    StringLocalization.healthGauge: 'healthGauge',
    StringLocalization.helpForMeasurement: 'measurment',
    StringLocalization.help: 'Help',
    StringLocalization.findBracelet: 'Find bracelet',
    StringLocalization.version: 'Version',
    StringLocalization.selectLanguage: 'Language',
    StringLocalization.overrideLanguageSetting: 'Override Language Setting',
    StringLocalization.localization: 'Localization',
    StringLocalization.language: 'Language',
    StringLocalization.chooseSelectedLanguage: 'Enable to change language',
    StringLocalization.english: 'English',
    StringLocalization.hindi: 'Hindi',
    StringLocalization.french: 'French',
    StringLocalization.spanish: 'Spanish',

    StringLocalization.ppgNoChartDataAvailable: 'No chart data available.',
    StringLocalization.enterTitle: 'Enter Title',
    StringLocalization.kSearchMailHint: 'Search Mail',
    StringLocalization.kInbox: 'Inbox',
    StringLocalization.kDrafts: 'Draft',
    StringLocalization.kTrash: 'Trash',
    StringLocalization.kSent: 'Sent',
    StringLocalization.appReminders: 'App Notifications',
    StringLocalization.fetchInBackground: 'Fetch data in background',
    StringLocalization.fetchAndNext: 'Fetch & Next',
    StringLocalization.doItInTheBackground: 'Do it in the background',
    StringLocalization.ifYouCanNotFindYourHGDevice:
        'If you can\'t find the name of your HG device on your scan list, try these solutions:',
    StringLocalization.makeSureItNotConnectedWithAnotherPhone:
        '1) Make sure your HG device is not paired with another phone.',
    StringLocalization.makeSureLocationPermission:
        '2) Make sure that the location permission is granted for the Health Gauge App.',
    StringLocalization.ifYouCanNotPair: 'If you can not pair your phone with your HG device:',
    StringLocalization.resetYourDevice: '1)  Reset your HG device.',
    StringLocalization.reminders: 'Reminders',
    StringLocalization.addReminders: 'Add Reminders',
    StringLocalization.updateReminders: 'Update Reminders',
    StringLocalization.call: 'Call',

    StringLocalization.message: 'Message',
    StringLocalization.qq: 'QQ',
    StringLocalization.weChat: 'WeChat',
    StringLocalization.linkedIn: 'LinkedIn',
    StringLocalization.skype: 'Skype',
    StringLocalization.facebookMessenger: 'Facebook Messanger',
    StringLocalization.twitter: 'Twitter',
    StringLocalization.whatsApp: 'WhatsApp',
    StringLocalization.viber: 'Viber',
    StringLocalization.line: 'Line',
    StringLocalization.kOutBox: 'Outbox',

    StringLocalization.onConnect: 'Successfully connected to socket...',
    StringLocalization.onConnectError: 'Error while connecting to socket,please try again!',
    StringLocalization.onConnectTimeout: 'Connection timeout!',
    StringLocalization.noClientFoundInNetwork: 'No client found in network!',

    StringLocalization.startTime: 'Start Time',
    StringLocalization.endTime: 'End Time',
    StringLocalization.intervalTime: 'Interval Time',
    StringLocalization.repeat: 'Repeat',
    StringLocalization.description: 'Description',
    StringLocalization.noteDescription: 'Short Description',
    StringLocalization.sun: 'S',
    StringLocalization.mon: 'M',
    StringLocalization.tue: 'T',
    StringLocalization.wed: 'W',
    StringLocalization.thu: 'T',
    StringLocalization.fri: 'F',
    StringLocalization.sat: 'S',
    StringLocalization.selectImage: 'Select Icon',
    StringLocalization.notification: 'Notification',
    StringLocalization.waterReminderTitle: 'Hydration',
    StringLocalization.dontForgetToDrinkWater: "Don't forget to drink water.",
    StringLocalization.sedentaryReminderTitle: 'Sedentary',
    StringLocalization.sedentaryDesc: "It's time to stand up.",
    StringLocalization.medicineReminderTitle: 'Medicine',
    StringLocalization.medicineDesc: 'Take your medication.',
    StringLocalization.leadOff: 'Lead Off',
    StringLocalization.leadDesc:
        'Please put your opposite hand\'s\nindex finger on the bottom of the bracelet.',

    StringLocalization.poorConductive: 'Poor Conductive',
    StringLocalization.poorConductiveDesc:
        'It is recommended to moisten\nthe water at the sensor contact.',

    StringLocalization.goodSignal: 'Good Signal',
    StringLocalization.readyForMeasurement: 'Ready For Measurement?',
    StringLocalization.measurementInProgress: 'Measurement In Progress',

    StringLocalization.holdHand:
        '1. Hold your hand still.\n2. The bracelet should be snug.\n3. Please put your opposite hand\'s index finger on the bottom of the bracelet.\n4. It is recommended Moisten your skin in the area of bracelet contact.',
    StringLocalization.graphdisclaimer:
        'In our mobile application, we prioritize the well-being and safety of our users. It\'s important to note that the data provided on this page is for informational purposes only and should not be interpreted as medical advice. We strongly advise all users to consult with a qualified medical professional before making any decisions or taking action based on the information provided within the application. Your health is paramount, and seeking guidance from a medical expert ensures that you receive personalized and accurate advice tailored to your individual needs and circumstances. Always prioritize your health and well-being by consulting with a healthcare professional for any concerns or questions you may have.',
    StringLocalization.braceletSung: '2) The bracelet should be snug.',
    StringLocalization.putYourFinger:
        '3) Please put your opposite hand\'s\nindex finger on the bottom of the bracelet.',
    StringLocalization.recommodateMoisten:
        '4) It is recommended Moisten your skin in the area of bracelet contact.',
    StringLocalization.doNotAskAgain: "Don't ask me again",
    StringLocalization.diet: 'Diet',
    StringLocalization.medicine: 'Medicine',
    StringLocalization.corona: 'Covid-19',
    StringLocalization.smoking: 'Smoking',
    StringLocalization.alcohol: 'Alcohol',
    StringLocalization.glucosepatch: 'Glucose Patch',
    StringLocalization.glucosepatchlocation: 'Glucose Patch Location',
    StringLocalization.fingerStick1Glucose: 'Finger Stick Glucose Measurement 1',
    StringLocalization.fingerStick2Glucose: 'Finger Stick Glucose Measurement 2',
    StringLocalization.allowance: 'Allowance',
    StringLocalization.search: 'Search',
    StringLocalization.more: 'More',
    StringLocalization.MMOLPerLiter: 'mmol/L',
    StringLocalization.MMGL: 'mg/dL',
    StringLocalization.measurementResult: 'Measurement Result',
    StringLocalization.measurementData: 'Your blood pressure estimation is :',
    StringLocalization.estimating: 'Estimation',
    StringLocalization.synchronization: 'Synchronization',
    StringLocalization.contacts: 'Contacts',
    StringLocalization.delete: 'Delete',
    StringLocalization.contactDeleted: 'Contact Deleted',
    StringLocalization.noContactFound: 'No Contact Found !!!',
    StringLocalization.invitations: 'Invitations',
    StringLocalization.searchContact: 'Search Contacts',
    StringLocalization.searchUser: 'Search Users',
    StringLocalization.noPendingInvitations: 'No Pending invitations',
    StringLocalization.noPendingInvitationToSearchFrom: 'No pending invitations to search from',
    StringLocalization.addContacts: 'Add contacts',
    StringLocalization.invitedSucessfully: 'Invited Successfully',
    StringLocalization.invitationFailed: 'Invitation Failed',
    StringLocalization.searchNameOfUser: 'Search name of the User',
    StringLocalization.pageDeleted: 'Page deleted',
    StringLocalization.pageAdded: 'Page Added',
    StringLocalization.youCanNotAddMorePages: 'You can not add more pages',
    StringLocalization.addPage: 'Add page',
    StringLocalization.deleteCurrentPage: 'Delete current page',
    StringLocalization.editTitleOfpage: 'Edit Category Title and Icon',
    StringLocalization.addTitleOfpage: 'Add Category Title and Icon',
    StringLocalization.editTitle: 'Title',
    StringLocalization.compose: 'Compose',
    StringLocalization.to: 'To',
    StringLocalization.cc: 'CC',
    StringLocalization.subject: 'Subject',
    StringLocalization.body: 'Compose Email',
    StringLocalization.enterAllFields: 'Fill all Fields',
    StringLocalization.pleaseEnterToSubject: 'Please select a contact and enter subject',
    StringLocalization.addToDrafts: 'Add to drafts',
    StringLocalization.draftConfirmation:
        'By Clicking OK you are confirming to save mail in drafts',
    StringLocalization.messageSentSuccessfully: 'Message sent successfully',
    StringLocalization.messageNotSent: 'Message not Sent',
    StringLocalization.untrash: 'Restore',
    StringLocalization.emailDeletedSuccessfully: 'Email deleted successfully',
    StringLocalization.selectAll: 'Select all',
    StringLocalization.emailRestoredSuccessfully: 'Email restored successfully',
    StringLocalization.detail: 'Detail',
    StringLocalization.from: 'From',
    StringLocalization.reply: 'Reply',
    StringLocalization.replyAll: 'Reply All',
    StringLocalization.forward: 'Forward',
    StringLocalization.requested: 'Requested',
    StringLocalization.helpPageUrl: 'asset/help.html',
    StringLocalization.healthKit: 'Health Kit',
    StringLocalization.googleFit: 'Google Fit',
    StringLocalization.alarm: 'Alarm',
    StringLocalization.addAlarm: 'Add Alarm',
    StringLocalization.selectDays: 'Select Days',
    StringLocalization.alarmLabel: 'Alarm Label',
    StringLocalization.selectTime: 'Select Time',

    StringLocalization.addNameForBluetoothDevice: 'Name this device',

    StringLocalization.enterName: 'Enter name',
    StringLocalization.hideFromList: 'Hide device from the list',
    StringLocalization.showAll: 'Show all',
    StringLocalization.hide: 'Hide',
    StringLocalization.allSleep: 'Sleep',
    StringLocalization.deepSleep: 'Deep sleep',
    StringLocalization.lightSleep: 'Light sleep',
    StringLocalization.ppgReminderTitle: 'PPG',
    StringLocalization.ppgDesc: 'Time For PPG.',
    StringLocalization.autoLoad: 'Auto Load',
    StringLocalization.systolic: 'Sys',
    StringLocalization.diastolic: 'Dia',
    StringLocalization.goal: 'Goal',
    StringLocalization.autoTagging: 'Measurement Tagging',
    StringLocalization.termsAndConditionPageUrl: 'asset/terms_and_condition.html',
    StringLocalization.awake: 'Awake',
    StringLocalization.chooseYourCaloriesTarget: 'Choose your calories target',
    StringLocalization.caloriesSuggestion:
        'Suggestion: women 1600 ~ 2400 calories a day and men 2000 ~ 3000 calories a day.',
    StringLocalization.caloriesTarget: 'Calories Target: ',
    StringLocalization.chooseYourDistanceTarget: 'Choose your distance target',
    StringLocalization.distanceTarget: 'Distance Target:',
    StringLocalization.distanceSuggestion: 'Suggestion: 5 ~ 7 km a day',
    StringLocalization.distanceSuggestionMile: 'Suggest 8 ~ 11 Miles a day',
    StringLocalization.normal: 'NORMAL',
    StringLocalization.hRNormal: 'Sitting',
    StringLocalization.resting: 'Resting',
    StringLocalization.walking: 'Walking',
    StringLocalization.exercising: 'Exercising',
    StringLocalization.slow: 'Slow',
    StringLocalization.fast: 'Fast',
    StringLocalization.whatStateAreYouMeasuringIn: 'What state are you measuring in?',
    StringLocalization.maxEffort: 'Max Effort',
    StringLocalization.hardCoreTraining: 'Hardcore',
    StringLocalization.enduranceTraining: 'Endurance',
    StringLocalization.fatBurning: 'Fat Burning',
    StringLocalization.normalization: 'Normalization',
    StringLocalization.weightMeasurement: 'Weight Measurement',
    StringLocalization.measuringKeepStanding: 'Measuring keep standing',
    StringLocalization.unStableWeight: 'Fluctuating weight',
    StringLocalization.onBoardNow: 'Please get on weight scale now',
    StringLocalization.measureComplete: 'Measurement Completed',
    StringLocalization.allMeasurementNotTaken: 'Incomplete measurement',
    StringLocalization.withinADay: 'Within a day',
    StringLocalization.deviceNotConnected: 'Device not connected',
    StringLocalization.overweight: 'OVER',
    StringLocalization.underweight: 'UNDER',
    StringLocalization.normalWeight: 'NORMAL',
    StringLocalization.ideal: 'Ideal',
    StringLocalization.thin: 'Thin',
    StringLocalization.obese: 'OBESE',
    StringLocalization.low: 'LOW',
    StringLocalization.preHyper: 'PRE',
    StringLocalization.hyper: 'HYPER',
    StringLocalization.high: 'HIGH',
    StringLocalization.alert: 'Alert',
    StringLocalization.danger: 'Danger',
    StringLocalization.excellent: 'Excellent',
    StringLocalization.bMI: 'BMI',
    StringLocalization.bfr: 'Body Fat Ratio',
    StringLocalization.muscleRate: 'Muscle Rate',
    StringLocalization.bodyWater: 'Body Water',
    StringLocalization.visceralFatIndex: 'Visceral Fat Index',
    StringLocalization.bmr: 'BMR',
    StringLocalization.proteinRate: 'Protein Rate',
    StringLocalization.boneMass: 'Bone Mass',
    StringLocalization.avgOfDay: 'Average of the day',
    StringLocalization.avgOfWeek: 'Average of the Week',
    StringLocalization.avgOfMonth: 'Average of the Month',
    StringLocalization.bodyMassIndex: 'Body Mass Index',
    StringLocalization.oscillometric: 'Oscillometric AI Verification',
    StringLocalization.tab: 'Tab',
    StringLocalization.editTitleOfGraph: 'Edit title of graph',
    StringLocalization.startDate: 'Start Date',
    StringLocalization.addWeightDescription: 'Please enter your weight',
    StringLocalization.selectUnit: 'Please select a unit',
    StringLocalization.researcherProfile: 'Researcher\nProfile',
    StringLocalization.researcherProfileTitle: 'Researcher Profile',
    StringLocalization.enterPassword: 'Enter Password',
    StringLocalization.enterPasswordText: 'Enter password to become a Researcher',
    StringLocalization.wrongPassword: 'Password is incorrect',
    StringLocalization.youAreResearcher: 'You are now a Researcher',
    StringLocalization.heartRateShortForm: 'HR',
    StringLocalization.notResearcher: 'You are not a researcher anymore',
    StringLocalization.Ai: 'AI',
    StringLocalization.sleepData: 'Sleep Data',
    StringLocalization.chooseYourWeightTarget: 'Choose your weight target',
    StringLocalization.weightTarget: 'Weight Target',
    StringLocalization.weightSuggestion: 'Suggestion: Your weight should be in range ',
    StringLocalization.tagNoteDeletedSuccessfully: 'Tag Note deleted successfully',
    StringLocalization.wrongData: 'Measurement Stopped!',
    StringLocalization.measurementNotStarted: 'Measurement Not Started!',
    StringLocalization.wrongDataDescription:
        'Measurement data is incorrect, do you want to restart measurement?',
    StringLocalization.measurementNotStartedDescription:
        'Seems like measurement is not getting started in the device. Please try again.',
    StringLocalization.restart: 'Restart',

    ///Added by: Shahzad
    ///Added on: 28/10/2020
    ///Contains string localisation for help page
    StringLocalization.HGOverview: 'Health Gauge Overview',
    StringLocalization.HGIntro:
        "Health Gauge is a platform for personal health monitoring and management. Users of the platform include the general public interested in health and wellness, care providers working with users, researchers that access the data in order to develop and deliver analytics, and business partners the provide goods and services to the Health Gauge community of users. The platform accepts connections from a variety of health devices as well as fitness wearables; however, users can use Health Gauge without a device to monitor and manage their health and work with their care team even if they don't have a health device.\nThe components of Health Gauge mobile application include the following:",
    StringLocalization.login: 'Login',
    StringLocalization.loginInfo:
        'Normally users log into the app and stay logged in unless they log out or stop the application.',
    StringLocalization.signUp: 'Sign Up',
    StringLocalization.signUpInfo:
        'User can use this page to register for an account. Once an account is created, the profile information for the account is stored locally but synchronized with the Health Gauge server. Note that the application can still be used without an account, but no data will be saved.',
    StringLocalization.resetPassword: 'Reset Password',
    StringLocalization.resetPasswordInfo: 'Users can request a password reset.',
    StringLocalization.home: 'Home',
    StringLocalization.homeInfo:
        'Home page is consisting of :\n1 -  Title bar \n2 - Main area \n3 - Navigation bar \n1 - The home page allows a person from the title bar to navigate to the profile page, Message centre, the connection and settings. \n2 - In the main area users can see Circle indicators, Progress bars , and guide bars bars. Circle indicators have different meanings depend on their type. \n3 - The navigation bar supports immediate access to Home, Graph, Measurement, Diary and Help page. ',
    StringLocalization.HGProfile: 'Profile',
    StringLocalization.profileInfo:
        "User profile data stores the user's picture, name, id, birthdate, height, weight, max weight, gender, skin color and researcher profile. This data is synchronized with the web server. Valid data is essential for the AI system because this data is used to calculate estimates.",
    StringLocalization.HGConnection: 'Connections',
    StringLocalization.connectionInfo:
        'The Connections page lists available BLE devices. Each device has an id associated with it and it is that id that displays in the connection list. User must select the device and "Connect". The device will stay connected continuously and will automatically reconnect if the connection is lost.',
    StringLocalization.HGSettings: 'Settings',
    StringLocalization.settingsInfo:
        'The settings page allows the user to access device management functions, set activity and sleep targets, view the version number, find the bracelet, and see historical measurements for activities, sleep, cardio and tags. The tag label editor is also accessible as well as the terms and conditions of use and the training flag (See below).',
    StringLocalization.cardioMeasurement: 'Cardio Measurement',
    StringLocalization.cardioMeasurementInfo:
        'The settings page allows the user to access device management functions, set activity and sleep targets, view the version number, find the bracelet, and see historical measurements for activities, sleep, cardio and tags. The tag label editor is also accessible as well as the terms and conditions of use and the training flag (See below).',
    StringLocalization.activityDay: 'Activity Day',
    StringLocalization.activityDayInfo:
        'Health Gauge tracks user steps. Based on profile information user calories and distance traveled is estimated. A week and month summary view of the data can be displayed. The data is stored locally and sent to the server. If not online, data is flagged for synchronization.',
    StringLocalization.activityWeeklyMonthly: 'Activity Weekly & Monthly Summary',
    StringLocalization.activityWeeklyMonthlyInfo:
        'The activity data is summarized on each graph with a weekly summary view or a monthly summary view.',
    StringLocalization.HGSleep: 'Sleep',
    StringLocalization.sleepInfo:
        'During the night, sleep is tracked based on motion. Sleep is measured in 15-minute increments and detects variations of awake, light-sleep, and deep-sleep. A color chart is displayed by time increment. A week and month summary view of the data can be displayed. The data is stored locally and sent to the server. If not online, data is flagged for synchronization.',
    StringLocalization.HGTag: 'Tag',
    StringLocalization.tagInfo:
        'A user can tag any reading they want at any time. 9 default tags are provided but the user can create more. Tags record a point of interest for a user that is not automatically captured by the device. For example, temperature, fatigue, blood glucose, eating, drugs, etc. The tag page allows a user to select the tag type, indicate a reading level and add notes if necessary.',
    StringLocalization.tagEditorList: 'Tag Editor List',
    StringLocalization.tagEditorListInfo:
        'This page appears in the settings area. It allows users to create or edit tags. (See Tag) The first screen is a list of available tags to edit. The user can click + to add another tag. Note that these tags are synchronized with the web site. User can delete tags or edit them.',
    StringLocalization.tagEditor: 'Tag Editor',
    StringLocalization.tagEditorInfo:
        'This appears as a popup and allows the user to edit the details of a tag. User can indicate tag label, the unit of measurement, the range of values allowed and the precision level. User can also select a default value.',
    StringLocalization.HGGraph: 'Graph',
    StringLocalization.graphInfo:
        'This page is a type of dashboard. Users can add widgets which are collections of measures over the selected period of time. A week and month summary view of the data can be displayed. Users can add or remove any widget. Each displayed widget can be edited to add or delete any measurement or tag value within the system.',
    StringLocalization.HGMeasurementHistory: 'Measurement History',
    StringLocalization.measurementHistoryInfo:
        'This option is available in settings. User can see the cardio measurements in day, week, or month groupings.',
    StringLocalization.HGTagHistory: 'Tag History',
    StringLocalization.tagHistoryInfo:
        'This option is available in settings. User can see the tag assignments in day, week, or month groupings.',
    StringLocalization.weightHelp: 'Weight',
    StringLocalization.moreFunctions: 'More Functions',
    StringLocalization.HGFindBracelet: 'Find Bracelet',
    StringLocalization.findBraceletInfo: 'Simple function to vibrate the connect device.',
    StringLocalization.HGliftTheWristBrighten: 'Lift The Wrist To Brighten Screen',
    StringLocalization.liftTheWristBrightenInfo:
        'Simple function that turns off or on the ability for the device to light up when the device is raised up.',
    StringLocalization.HGDoNotDisturb: 'Do Not Disturb',
    StringLocalization.doNotDisturbInfo: 'Simple option to turn off vibration at night.',
    StringLocalization.HGTimeFormat: 'Time Format',
    StringLocalization.timeFormatInfo:
        'Time can be displayed on the device in 12 or 24 hour time format.',
    StringLocalization.HGWearingMethod: 'Wearing Method',
    StringLocalization.wearingMethodInfo:
        'Indicates whether to wear the device on the left or right hand. Functionality is the same but the ECG is inverted on the right wrist.',
    StringLocalization.HGTraining: 'Training',
    StringLocalization.trainingInfo:
        'This is an option available in the settings page that allows a user to enter training data. By entering data that corresponds their profile a user can boost the accuracy of the Blood Pressure assessments.',
    StringLocalization.HGhrMonitor: 'Hourly HR Monitor',
    StringLocalization.hrMonitorInfo:
        'This is an option available in the device management page. This setting allows the device to record hourly readings.',
    StringLocalization.references: 'References',

    StringLocalization.weightUrl:
        'https://www.nursingcenter.com/ncblog/august-2017/body-mass-index-and-body-surface-area-what-s-the-d',
    StringLocalization.bpUrl:
        'http://www.bloodpressureuk.org/your-blood-pressure/understanding-your-blood-pressure/what-do-the-numbers-mean/',
    StringLocalization.sleepUrl:
        'https://www.corvallisclinic.com/sleep-medicine/understanding-your-sleep-study/',
    StringLocalization.hrUrl:
        'https://myheart.net/articles/what-is-a-normal-heart-rate/#:~:text=What%20is%20a%20Normal%20or,than%20100%20beats%20per%20minute',
    StringLocalization.furtherInfoBp:
        'For further information regarding blood pressure refer this link : ',
    StringLocalization.furtherInfoHr:
        'For further information regarding heart rate refer this link : ',
    StringLocalization.furtherInfoWeight:
        'For further information regarding weight and BMI refer this link : ',
    StringLocalization.furtherInfoSleep:
        'For further information regarding sleep refer this link : ',

    StringLocalization.maxWeight: 'Initial Weight',
    StringLocalization.initialWeightTitle: 'Initial\nWeight',

    StringLocalization.deleteGraph: 'Are you sure you want to delete this graph?',
    StringLocalization.no: 'No',
    StringLocalization.yes: 'Yes',
    StringLocalization.selectColor: 'Select color',
    StringLocalization.MMOL: 'mmol/L',
    StringLocalization.MGDL: 'mg/dL',
    StringLocalization.fahrenheit: 'Fahrenheit',
    StringLocalization.glass: 'Glass',
    StringLocalization.running: 'Running',
    StringLocalization.hiking: 'Hiking',
    StringLocalization.biking: 'Biking',
    StringLocalization.easy: 'Easy',
    StringLocalization.moderate: 'Moderate',
    StringLocalization.selectGraphType: 'Select graph type',
    StringLocalization.lineGraph: 'Line',
    StringLocalization.barGraph: 'Bar',
    StringLocalization.lineAndBarGraph: 'Line and Bar',
    StringLocalization.deviceData: 'Device data',
    StringLocalization.titleDbp: 'Diastolic BP',
    StringLocalization.result: 'Result',
    StringLocalization.AIData: 'AI Estimate data',
    StringLocalization.userData: 'Data entered by user',
    StringLocalization.aDayAgo: 'A day ago',
    StringLocalization.daysAgo: 'Days ago',
    StringLocalization.endDate: 'End Date',
    StringLocalization.collectData: 'Collect Data',
    StringLocalization.addGraphRestriction: "You can't add more than two types",
    StringLocalization.meter: 'Meter',
    StringLocalization.titleSbp: 'Systolic BP',
    StringLocalization.changesNotSaved: 'Changes are not saved',
    StringLocalization.notSavedDescription: 'Do you want to save your changes?',
    StringLocalization.initialWeightInfo:
        'It is the weight of user at the time of installing the app',
    StringLocalization.brightness: 'Brightness',
    StringLocalization.Low: 'Low',
    StringLocalization.Medium: 'Medium',
    StringLocalization.High: 'HIGH',
    StringLocalization.homeScreenItems: 'Home Screen Items',
    StringLocalization.tagLevel: 'Level of ',
    StringLocalization.numberOfPills: 'Number of Pills',
    StringLocalization.glassOf: 'Glasses of Drink',
    StringLocalization.numberOfSmoke: 'Number of Smokes',
    StringLocalization.start: 'Start',

    StringLocalization.normalCalibration: 'Normal',
    StringLocalization.lowCalibration: 'Low',
    StringLocalization.highCalibration: 'High',
    StringLocalization.hyperCalibration: 'Moderately High',
    StringLocalization.highHyperCalibration: 'Severely High',

    StringLocalization.gmail: 'Gmail',
    StringLocalization.instagram: 'Instagram',
    StringLocalization.snapchat: 'Snapchat',
    StringLocalization.facebook: 'Facebook',
    StringLocalization.weibo: 'Weibo',
    StringLocalization.syncHealthKit: 'Sync Health Kit Data',
    StringLocalization.syncGoogleFit: 'Sync Google Fit Data',
    StringLocalization.clickAgain: 'press back again to exit',
    StringLocalization.surveyList: 'Survey List',
    StringLocalization.addSurvey: 'Add Survey',
    StringLocalization.addQuestion: 'Add Question',
    StringLocalization.backText: 'Back',
    StringLocalization.selectServer: 'Select Server',
    StringLocalization.changeQuestionType: 'Choose Question Type',
    StringLocalization.calendarScreen: 'Calendar',
    StringLocalization.survey: 'Survey',
    StringLocalization.temperatureMonitoring: 'Temperature Monitoring',
    StringLocalization.kSend: 'Send',
    StringLocalization.trends: 'Trends',
    StringLocalization.hrBPMonitoring: 'HR And BP Monitoring',
    StringLocalization.bpMonitoring: 'BP Monitoring',

    StringLocalization.interpolation: 'Intrpl',
    StringLocalization.confirmationText: 'Do you want to continue?',
    StringLocalization.cameraMeasurement: 'Camera Measurement',
    StringLocalization.hg08Name: 'HG Genesis',
    StringLocalization.hg66Name: 'Genesis O2',
    StringLocalization.hg80Name: 'HG Phoenix',
    StringLocalization.bluetooth: 'Bluetooth',
    StringLocalization.cmShort: 'cm',
    StringLocalization.inchShort: 'in',
    StringLocalization.feetShort: 'ft',
    StringLocalization.celsiusShort: '°C',
    StringLocalization.fahrenheitShort: '°F',
    StringLocalization.unitSetSuccess: 'Unit set successfully',
    StringLocalization.deviceSetSuccess: 'Device set successfully',
    StringLocalization.intensity: 'Intensity',
    StringLocalization.searchIcon: 'Search Icons',
    StringLocalization.addNewTag: 'Add New Tag',
    StringLocalization.selectCategory: 'Select the Category',
    StringLocalization.wellness: 'Wellness',
    StringLocalization.exerciseTitle: 'New Exercise Tag',
    StringLocalization.wellnessTitle: 'New Wellness Tag',
    StringLocalization.symptomsTitle: 'New Symptoms Tag',
    StringLocalization.emptyWeight: 'Enter Weight',
    StringLocalization.enterHeight: 'Enter Height',
    StringLocalization.voiceConfiguration: 'Text to Speech Setting',
    StringLocalization.takePhoto: 'Take Photo',
    StringLocalization.photoLibrary: 'Photo Library',
    StringLocalization.noConnectionMessage: 'Device Not Connected. Please connect a device.',
    StringLocalization.connectAgain: 'Unable to connect device try again.',
    StringLocalization.addNewGraphTab: 'Do you want to add a new Category?',
    StringLocalization.addNewCategory: 'Add New Category',
    StringLocalization.selectIcon: 'Select Icon',
    StringLocalization.emptyTitle: 'Enter Title',
    StringLocalization.deleteInfo: 'Are you sure you want to delete this graph?',
    StringLocalization.nothingToShow: 'Nothing to Show.',
    StringLocalization.tts: 'Text To Speech',
    StringLocalization.speed: 'Speed',
    StringLocalization.selectVoice: 'Select Voice',
    StringLocalization.stt: 'Speech To Text',
    StringLocalization.selectYourDevice: 'Select your device',
    StringLocalization.logOutConfirmMsg: 'Are you ready to log out?',
    StringLocalization.wifiConnectMsg: 'Connect wifi for transfer data',
    StringLocalization.yourBp: 'Your BP:',
    StringLocalization.noData: 'No Data',
    StringLocalization.sysAvg: 'Systolic Average',
    StringLocalization.diaAvg: 'Diastolic Average',
    StringLocalization.userRegisteredSuccessfully: 'Successfully signed up',
    StringLocalization.userLoggedInSuccessfully: 'Successfully signed in',
    StringLocalization.tagDeleteInfo: 'Are you sure you want to delete this tag?',
    StringLocalization.alreadyUsedName: 'This Tag label already exists.',
    StringLocalization.noIconFound: 'No Icon Found!',
    StringLocalization.disclaimerInfo:
        "Health gauge app and its device is an aid, designed to help you improve your life quality.  It does not substitute for medical advice or diagnosis and doing so might have serious health consequences.\n\nThe Health Gauge Phoenix+FIT and application is to be used to consolidate and track health metrics that will allow for a more comprehensive overview of current health management. Under no circumstances is the Health Gauge Phoenix+FIT to directly impact the diagnosis, treatment, or management of an individual's disease.\n\nThe Phoenix+FIT application has been designed to serve as a means of personal health monitoring and tracking and is intended to be used to maintain a healthy lifestyle, and understand one's health and is, therefore, a wellness device. In no case is the software and AI technology utilized by Health Gauge to replace the professional clinical judgment of a health care professional.\n\nIf you think that you have a medical problem, please consult your doctor.\n\nWHEN SUPPORTED FOR INVESTIGATIONAL USE:\n\nWhere the Health Gauge application is supported for clinical research, or investigational use by Health Canada and/or the US Food and Drug Administration, it should only be used as indicated and by qualified Investigators only.\n\nWhen a user requests the deletion of their account, it is important to note that while their account information will be removed from active databases, certain data associated with their account may still be retained for training and research purposes. This retained data, anonymized or aggregated, contributes to service improvement and research advancements. Users can reach out to Health Gauge with any concerns regarding data handling after account deletion.",
    StringLocalization.disclaimer: 'Disclaimer',
    StringLocalization.imageIsEmpty: "Image can't be empty. Please select an Image.",
    StringLocalization.healthKitNotAvailableOnDevice: 'Health Kit is not available on your device',
    StringLocalization.information: 'Information',
    // StringLocalization.glucoseCalibrationHelp: 'Information',

    StringLocalization.glucoseCalibrationHelp:
        'In order to calibrate the P5.0 Glucose device, Two Finger stick glucose measurements are required. Please take two measurements using your Finger stick glucose device and into the calibration page. Please make sure that all of the field are completed with accurate information and both measurements are in the same unit. Failing to provide accurate information might result in an inaccurate estimate by the Patch.',

    StringLocalization.overWeightText: 'OverWeight',
    StringLocalization.obeseText: 'Obese',
    StringLocalization.addAnEvent: 'Add an Event',
    StringLocalization.appointment: 'Appointment',

    StringLocalization.minutes: 'Minutes',
    StringLocalization.yourEvents: 'Your Events',
    StringLocalization.eventNotAdded: 'Event Not Added',
    StringLocalization.eventNotdeleted: 'Event Not deleted',
    StringLocalization.reminder: 'Reminder',
    StringLocalization.reminderNotAdded: 'Reminder Not Added',
    StringLocalization.taskNotAdded: 'Task Not Added',
    StringLocalization.appointmentNotBooked: 'Appointment Not Booked',
    StringLocalization.allDay: 'All day',
    StringLocalization.setDate: 'Set Date',
    StringLocalization.setTime: 'Set Time',
    StringLocalization.outOfTown: 'Out of Town',
    StringLocalization.autoDeclineNewOrExistingMeetings:
        'Automatically decline new or existing meetings and conferencing',
    StringLocalization.task: 'Task',
    StringLocalization.noResultFound: 'No Result found',
    StringLocalization.createFolder: 'Create Folder',
    StringLocalization.noRecordsFound: 'No Records Found',
    StringLocalization.oopsDoSomething: 'Oops!! Do Something',
    StringLocalization.allMailsAlreadyRead: 'All emails have been read.',
    StringLocalization.pleaseWait: 'Please wait',
    StringLocalization.noTagsFound: 'No tags found',
    StringLocalization.emailSavedInOutbox: 'Email Saved in outbox successfully',
    StringLocalization.iAccept: 'I accept ',
    StringLocalization.agreeDisclaimerText: 'Please Accept the Disclaimer.',
    StringLocalization.studyCodeText:
        'If you know the study or practice code please insert it, other wise leave it blank.',
    StringLocalization.hintForStudyCode: 'Study/Practice code',
    StringLocalization.userRegisteredText:
        'Thanks for your registration. Once the registration has been processed, you’ll receive a confirmation code in your email.',
    StringLocalization.iAcceptThe: 'I accept the ',
    StringLocalization.resendCodeText:
        'If you did not receive a code, click below to get the code.',
    StringLocalization.resendCode: 'Resend Code',
    StringLocalization.enterDate: 'Enter Date (dd/mm/yyyy)',
    StringLocalization.saveDataInGoogleFit: 'Save data in Google Fit',
    StringLocalization.activityTrackScreen: 'Activity Tracker',
    StringLocalization.finish: 'Finish',
    StringLocalization.pause: 'Pause',
    StringLocalization.resume: 'Resume',
    StringLocalization.incorrectMeasurement: 'Measurement failed',
    StringLocalization.sleepReminder: 'Sleep Reminder',
    StringLocalization.enable: 'Enable',
    StringLocalization.activityHistory: 'Activity History',
    StringLocalization.sleepReminderSetSuccessfully: 'Sleep Reminder set successful!',
    StringLocalization.discard: 'Discard',
    StringLocalization.weightMeasurementDialog:
        'Did not get data from weight scale, Please try again.',
    StringLocalization.chat: 'Chat',
    StringLocalization.wifiConnect: 'UOFA',
    StringLocalization.library: 'HG Drive',
    StringLocalization.hrZone: 'Heart Rate Zones',
    StringLocalization.hrZoneHistory: 'HR Zone Report',
    
    StringLocalization.deletePermanently: 'Delete Permanently',
    StringLocalization.shareWithUser: 'Share With User',
    StringLocalization.shareSuccessMessage: 'Successfully shared.',
    StringLocalization.shareFailureMessage: 'Failed to share.',
    StringLocalization.shareLink: 'Share Link',
    StringLocalization.createdFolderSuccessfully: 'Created Folder Successfully',
    StringLocalization.deletedFileFolderSuccessfully: 'Deleted File/Folder Successfully',
    StringLocalization.restoredFileFolderSuccessfully: 'Restored File/Folder Successfully',
    StringLocalization.uploadedSuccessfully: 'Uploaded Successfully',
    StringLocalization.hgSyncedSuccessfully: 'HG Watch has been Synced Successfully',
    StringLocalization.errorWhileUploading: 'Error While Uploading',
    StringLocalization.errorWhileDeleting: 'Error While Deleting',
    StringLocalization.yoursFilesAreUploading: 'Your files are uploading',
    StringLocalization.sortBy: 'Sort By',
    StringLocalization.shareWithMe: 'Share With Me',
    StringLocalization.bin: 'Bin',
    StringLocalization.myDrive: 'MyDrive',
    StringLocalization.name: 'Name',
    StringLocalization.lastModified: 'Last Modified',
    StringLocalization.lastModifiedByMe: 'Last Modified By Me',
    StringLocalization.lastOpenedByMe: 'Last Opened By Me',
    StringLocalization.searchInDrive: 'Search in Drive',
    StringLocalization.createNew: 'Create New',
    StringLocalization.create: 'Create',
    StringLocalization.savedSurvey: 'Saved Survey',
    StringLocalization.sharedSurvey: 'Shared Survey',
    StringLocalization.folder: 'Folder',
    StringLocalization.upload: 'Upload',
    StringLocalization.deleteDialogMessage: 'Are you sure you want to delete?',
    StringLocalization.instruction: 'Instruction',
    StringLocalization.camMeasurementInstruction1:
        'Heart Rate Monitor requires a well-lit environment to work.  If your camera has flash, it will be switched on automatically.',
    StringLocalization.camMeasurementInstruction2:
        'If your camera has no flash, you may be requested to use an additional lighting source to reduce noise.',
    StringLocalization.camMeasurementInstruction3:
        'To increase accuracy, don’t move or change the pressure of your finger during the measurement process.',
    StringLocalization.done: 'Done',
    StringLocalization.history: 'Measurements',
    StringLocalization.weightHistory: 'Weight History',
    StringLocalization.cardiacHistory: 'Cardiac History',
    StringLocalization.bodyMass: 'Body Mass',
    StringLocalization.requestTimeOUt: 'Request Timeout',
    StringLocalization.bodyMass: 'Body Mass',
    StringLocalization.workoutRecord: 'Workout Record',
    StringLocalization.pace: 'Speed (km/hr)',
    StringLocalization.pace1: 'Speed (Mile/hr)',
    StringLocalization.avgPace: 'Avg Speed (km/hr)',
    StringLocalization.avgPace1: 'Avg Speed (Mile/hr)',
    StringLocalization.duration: 'Duration',
    StringLocalization.startWorkout: 'Start Workout',
    StringLocalization.pause: 'Pause',
    StringLocalization.friends: 'Friends',
    StringLocalization.distanceKm: 'Distance (Km)',
    StringLocalization.morningWalk: 'Morning Walk',
    StringLocalization.howWasYourRun: 'How was your run?',
    StringLocalization.typeNotesHere: 'Type Notes here',
    StringLocalization.saveWorkout: 'Save Workout',
    StringLocalization.temperatureHistory: 'Temperature History',
    StringLocalization.oxygenHistory: 'Oxygen History',
    StringLocalization.spO2: 'SPO2',
    StringLocalization.forgotPassword: 'Password',
    StringLocalization.forgotId: 'Forgot ID',
    StringLocalization.oxygenMonitoring: 'SPO2 Monitoring',
    StringLocalization.updateFirmware: 'Update Firmware',
    StringLocalization.emptyTrashNow: 'Empty Trash Now',
    StringLocalization.inboxIsEmpty: 'Inbox is Empty',
    StringLocalization.sentIsEmpty: 'Sent is Empty',
    StringLocalization.draftIsEmpty: 'Draft is Empty',
    StringLocalization.trashIsEmpty: 'Trash is Empty',
    StringLocalization.outboxIsEmpty: 'Outbox is Empty',
    StringLocalization.firstNameValidation:
        'First name must be minimum 2 to maximum 50 characters long',
    StringLocalization.lastNameValidation:
        'Last name must be minimum 2 to maximum 50 characters long',
    StringLocalization.termsOfService: 'Terms of Service',
    StringLocalization.invitationAcceptedSuccessfully: 'Invitation Accepted Successfully',
    StringLocalization.shutDown: 'Shutdown',
    StringLocalization.shutDownWatch: 'Smartwatch Shutdown',
    StringLocalization.noEventsFound: 'No events found',
    StringLocalization.cardiac: 'Cardiac',
    StringLocalization.areYouSureWantToStopMeasurement: 'Are you sure want to stop measurement?',
    StringLocalization.viewData: 'View Data',
    StringLocalization.dataCollected: 'Data Collected',
    StringLocalization.january: 'January',
    StringLocalization.february: 'February',
    StringLocalization.march: 'March',
    StringLocalization.april: 'April',
    StringLocalization.may: 'May',
    StringLocalization.june: 'June',
    StringLocalization.july: 'July',
    StringLocalization.august: 'August',
    StringLocalization.september: 'September',
    StringLocalization.october: 'October',
    StringLocalization.november: 'November',
    StringLocalization.december: 'December',
    StringLocalization.notificationCenter: 'Notification Center',
    StringLocalization.heartRateHistory: 'Heart Rate',
    StringLocalization.hgServer: 'HG Server',
    StringLocalization.enableBle: 'Turn on Bluetooth for scanning your devices.',
    StringLocalization.goToSetting: 'Turn On',
    StringLocalization.touchElectrod: 'Touch the electrode',
    StringLocalization.areYouReadyToEmptyYourTrash: 'Are you ready to empty the trash?',
    StringLocalization.messageDeletedFromTrashSuccessfully:
        'Message Deleted From Trash Successfully',
    StringLocalization.changePassword: 'Change Password',
    StringLocalization.voiceSetting: 'Voice Setting',
    StringLocalization.oldPassword: 'Old Password',
    StringLocalization.confirmNewPassword: 'Confirm New Password',
    StringLocalization.oldPasswordDoesNotMatch: 'Old Password Does not match',
    StringLocalization.fail: 'Failed to connect',
    StringLocalization.connectionFailReasons: 'It can not be connected if:',
    StringLocalization.itCanNotBeConnect: 'It can not be connected if:',
    StringLocalization.failingToPhone: 'Watch failing for connecting to your phone',
    StringLocalization.restartPhone: 'Restart your phone',
    StringLocalization.deviceConnectedSomewhereElse: 'Your device is connected somewhere else',
    StringLocalization.disconnectFromThere: 'Disconnect your watch from there or restart watch',
    StringLocalization.disconnectFromThereBle:
        'Disconnect your BLE Device from there or restart BLE ',
    StringLocalization.isNotYourWatchScanning: 'Isn\'t your watch getting scan here?',
    StringLocalization.itCouldBecauseDeviceConnectedSomewhereElse:
        '1) It could because your device is connected somewhere else.',
    StringLocalization.locationPermissionNotGranted:
        '2) Location permission is not granted or location service is disable.',
    StringLocalization.givePermissionAndEnableLocation:
        'Give permission for access location and enable location service.',
    StringLocalization.deviceBluetoothNotFunctioningWell:
        '3) Device bluetooth is not functioning well.',
    StringLocalization.or: 'Or',
    StringLocalization.measurementType: 'Measurement Type',
    StringLocalization.notice: 'Notice',
    StringLocalization.forgotUserId: 'Forgot User ID',
    StringLocalization.downloadFirmware: 'Download Firmware',
    StringLocalization.auto_sync_data: 'Auto sync',
    StringLocalization.onlyMe: 'Only Me',
    StringLocalization.everyone: 'Everyone',
    StringLocalization.saySomethingAboutThisPhoto: 'Say something about this photos',
    StringLocalization.workoutPhotos: 'Workout Photos',
    StringLocalization.basedOnYourMaxHeartRate: 'Based on your max heart rate',
    StringLocalization.heartRateZones: 'Heart Rate Zones',
    StringLocalization.earlier: 'Earlier',
    StringLocalization.news: 'New',
    StringLocalization.notifications: 'Notifications',
    StringLocalization.workoutFeeds: 'Workout Feeds',
    StringLocalization.comment: 'Comment',
    StringLocalization.likes: 'likes',
    StringLocalization.viewAnalysis: 'View Analysis',
    StringLocalization.workoutAnalysis: 'Workout Analysis',
    StringLocalization.elevation: 'Elevation',
    StringLocalization.microphone: 'Microphone',
    StringLocalization.resend: 'Resend',
    StringLocalization.pleaseEnterTheSixDigitCodeSentToYourEmail:
        'Please enter the six-digit code sent to your email.',
    StringLocalization.pleaseEnterTheSixDigitCodeSentToYourPhone:
        'Please enter the six-digit code sent to your phone number.',
    StringLocalization.verify: 'Verify',
    StringLocalization.pleaseEnterYourNewPassword: 'Please enter your new password',
    StringLocalization.addPassword: 'Add Password',
    StringLocalization.verificationCode: 'Verification Code',
    StringLocalization.errorWhileRequestTryAgainLater: 'Error while request, try again later.',
    StringLocalization.noRecordWithUserId:
        'We don’t have any record with this user Id in our system.',
    StringLocalization.incorrectUserId: 'Incorrect User ID',
    StringLocalization.error: 'Error',
    StringLocalization.noPhoneNumberAssociated: 'No phone number is associated with your account.',
    StringLocalization.noEmailAssociated: 'No Email is associated with your account.',
    StringLocalization.whereAuthenticationCode:
        'Please select where you want your authentication code to be sent.',
    StringLocalization.passwordChangedSuccessfully: 'Password changed successfully',
    StringLocalization.min8toMax20: 'Must be minimum 8 to maximum 20 characters long',
    StringLocalization.oneUppercase: 'Must contain at least one uppercase letter',
    StringLocalization.oneLowercase: 'Must contain at least one lowercase letter',
    StringLocalization.oneSpecialCharacter: 'Must contain at least one special character',
    StringLocalization.oneNumber: 'Must contain at least one number',
    StringLocalization.agree: 'Agree',
    StringLocalization.disagree: 'Disagree',
    StringLocalization.oldNewPassword: 'Old and New password must be different.',
    StringLocalization.measurementStartFailed:
        'Start measurement failed! Would you like to start it again?.',
    StringLocalization.failed: 'Failed',
    StringLocalization.hrvRmssd: 'HRV (RMSSD)',
    StringLocalization.rememberMe: 'Remember Me',
    StringLocalization.readDisclaimer: 'Please read disclaimer before sign up',
    StringLocalization.readTermsAndConditions: 'Please read terms and conditions before sign up',
    StringLocalization.bloodPressureHistory: 'BP Trend Estimate',
    StringLocalization.weightConnectionType: 'Weight Connection Type',
    StringLocalization.enterValidWeight: 'Enter valid Weight',
    StringLocalization.maxWeightLimit: 'Enter weight less than',
    StringLocalization.enterValidHeight: 'Enter valid Height',
    StringLocalization.maxHeightLimitCm: 'Enter height less than 241 cm',
    StringLocalization.enterFeet: 'Enter Feet',
    StringLocalization.enterInch: 'Enter Inch',
    StringLocalization.maxHeightLimitFeet: 'Enter height less than 7 ft and 11 inch',
    StringLocalization.inchLimit: 'Inch cannot be greater than 12',
    StringLocalization.graphNormalization: 'Normalization',
    StringLocalization.tagNoteDeleteInfo: 'Are you sure you want to delete this tag note?',
    StringLocalization.measurementDeleteInfo: 'Are you sure you want to delete this measurement?',
    StringLocalization.discardWorkout: 'Discard Workout',
    StringLocalization.areYouSureYouWantToDiscardTheWorkout:
        'Are you sure you want to discard the workout?',
    StringLocalization.pleaseConnectTheInternet: 'Please connect the internet',
    StringLocalization.close: 'Close',
    StringLocalization.maxSpeed: 'Max Speed(KM/HR)',
    StringLocalization.hrvInfo:
        'Heart Rate Variability, HRV, is the variation in the interval between heartbeats. HRV always goes up when someone is feeling better. The goal is usually to shoot for the highest HRV reading you can get over time, though you should expect to have a few dips when training hard.\n\nThis variation is controlled by a primitive part of the nervous system called the autonomic nervous system (ANS) which also controls our heart rate, blood pressure, breathing, and digestion.\n\nIf we have persistent instigators such as stress, poor sleep, unhealthy diet, dysfunctional relationships, isolation or solitude, and lack of exercise, your fight-or-flight response can shift into overdrive causing a lower HRV number. If one is in a more relaxed state, the variation between beats is high.\n\nHRV is an interesting and noninvasive way to identify these ANS imbalances. Over the past few decades, research has shown a relationship between low HRV and worsening depression or anxiety. A low HRV is even associated with an increased risk of death and cardiovascular disease.\n\n\nSource: Harvard Medical School',
    StringLocalization.forReference: 'For more reference please click on the link below:\n',
    StringLocalization.tempInfo:
        'Normal human body temperature (normothermia,euthermia) is the typical temperature range found in humans. The normal human body temperature range is typically stated as 36.5–37.5°C (97.7–99.5°F).\nHuman body temperature varies. It depends on sex, age, time of day, exertion level, health status (such as illness and menstruation), what part of the body the measurement is taken at, state of consciousness (waking, sleeping, sedated), and emotions. Body temperature is kept in normal range by thermoregulation, in which adjustment of temperature is triggered by the central nervous system.\n\nHot\n•    44°C (111.2°F) or more – Almost certainly death will occur; however, people have been known to survive up to 46.5°C (115.7°F).\n•    43°C (109.4°F) – Normally death, or there may be serious brain damage, continuous convulsions and shock. Cardio-respiratory collapse will likely occur.\n•    42°C (107.6°F) – Subject may turn pale or remain flushed and red. They may become comatose, be in severe delirium, vomiting, and convulsions can occur. Blood pressure may be high or low and heart rate will be very fast.\n•    41°C (105.8°F) – (Medical emergency) – Fainting, vomiting, severe headache, dizziness, confusion, hallucinations, delirium and drowsiness can occur. There may also be palpitations and breathlessness.\n•    40°C (104°F) – Fainting, dehydration, weakness, vomiting, headache, breathlessness and dizziness may occur as well as profuse sweating. Starts to be life-threatening.\n•    39°C (102.2°F) – Severe sweating, flushed and red. Fast heart rate and breathlessness. There may be exhaustion accompanying this. Children and people with epilepsy may be very likely to get convulsions at this point.\n•    38°C (100.4°F) – (Classed as hyperthermia if not caused by a fever) – Feeling hot, sweating, feeling thirsty, feeling very uncomfortable, slightly hungry. If this is caused by fever, there may also be chills.\n\nNormal\n•    36.5–37.5°C (97.7–99.5°F) is a typically reported range for normal body temperature.\n\nCold\n•    36°C (96.8°F) – Feeling cold, mild to moderate shivering. Body temperature may drop this low during sleep. May be a normal body temperature.\n•    35°C (95°F) – (Hypothermia is less than 35°C (95°F)) – Intense shivering, numbness and bluish/grayness of the skin. There is the possibility of heart irritability.\n•    34°C (93.2°F) – Severe shivering, loss of movement of fingers, blueness and confusion. Some behavioural changes may take place.\n•    33°C (91.4°F) – Moderate to severe confusion, sleepiness, depressed reflexes, progressive loss of shivering, slow heart beat, shallow breathing. Shivering may stop. Subject may be unresponsive to certain stimuli.\n•    32°C (89.6°F) – (Medical emergency) – Hallucinations, delirium, complete confusion, extreme sleepiness that is progressively becoming comatose. Shivering is absent (subject may even think they are hot). Reflex may be absent or very slight.\n•    31°C (87.8°F) – Comatose, very rarely conscious. No or slight reflexes. Very shallow breathing and slow heart rate. Possibility of serious heart rhythm problems.\n•    28°C (82.4°F) – Severe heart rhythm disturbances are likely and breathing may stop at any time. Patient may appear to be dead.\n•    24–26°C (75.2–78.8°F) or less – Death usually occurs due to irregular heart beat or respiratory arrest; however, some patients have been known to survive with body temperatures as low as 14.2°C (57.6°F)',
    StringLocalization.spO2Info:
        'What is blood oxygen saturation(Spo2)?\nBlood oxygen saturation (SpO2) is the percentage of hemoglobin in the blood that contains oxygen- in other words, the amount of oxygen in the blood. It is a useful natural indicator of the condition of a person\'s respiratory system. If your SpO2 is below 90%, you may be at risk of developing hypoxemia. Generally speaking,the lower your SpO2 is below 90%, you may be at risk of developing hypoxemia. Generally speaking,the lower your SpO2,the higher the risk. Use the data below for reference:\n\n● ≥ 95%\n● < 90%\n\nNote: This device\'s measurement range is 50%-100%\n\nImportant things to note when measuring SpO2\n1. Enable the Spo2 feature on the wearable device Follow the instructions on your device to ensure the most accurate results.\n2. Certain external factors may interfere with the measurement, causing it to be inaccurate or even fail These include low blood flow, arm hair, tattoos, flabby skin, moving your arm during the measurement, not wearing your device correctly, room temperature, and so on.\n3.Measurement results are for reference only and are not intended as a basis for medical diagnosis.',
    StringLocalization.bpInfo:
        'Data presented is for information, and not considered as medical data.\n\nThis band is not intended for medical use. Please consult your physician for health related concerns.\n\nThe five blood pressure ranges as recognized by the American Heart Association are:\n\nNormal - Blood pressure numbers of less than 120/80 mm Hg are considered within the normal range. If your results fall into this category, stick with heart-healthy habits like following a balanced diet and getting regular exercise.\n\nElevated - Elevated blood pressure is when readings consistently range from 120-129 systolic and less than 80 mm Hg diastolic. People with elevated blood pressure are likely to develop high blood pressure unless steps are taken to control the condition.\n\nHypertension Stage 1 - Hypertension Stage 1 is when blood pressure consistently ranges from 130-139 systolic or 80-89 mm Hg diastolic. At this stage of high blood pressure, doctors are likely to prescribe lifestyle changes and may consider adding blood pressure medication based on your risk of atherosclerotic cardiovascular disease (ASCVD), such as heart attack or stroke..\n\nHypertension Stage 2 - Hypertension Stage 2 is when blood pressure consistently ranges at 140/90 mm Hg or higher. At this stage of high blood pressure, doctors are likely to prescribe a combination of blood pressure medications and lifestyle changes.\n\nHypertensive crisis - This stage of high blood pressure requires medical attention. If your blood pressure is higher than 180/120 mm Hg and you are experiencing signs of possible organ damage such as chest pain, shortness of breath, back pain, numbness/weakness, change in vision or difficulty speaking, do not wait to see if your pressure comes down on its own. Call for emergency medical help immediately.\n\nNote: A diagnosis of high blood pressure must be confirmed with a medical professional. A doctor should also evaluate any unusually low blood pressure readings.\n\nSource: American Heart Association',

    StringLocalization.ble_devices: 'Ble Devices',
    StringLocalization.transmit_command: 'Transmit Command',
    StringLocalization.connect: 'Connect',
    StringLocalization.device_connect_successfully: 'Device Connect Successfully',
    StringLocalization.enter: 'Enter',

    StringLocalization.consentTitle:
        'This non-invasive blood pressure solution utilizes PPG/ECG technology to estimate certain health metrics (Systolic Blood pressure and Diastolic Blood Pressure). It is crucial to understand the following terms and conditions before using this system:',
    StringLocalization.cInfoTitle: 'Informational Purposes Only:',
    StringLocalization.cInfoData:
        'The estimations and information provided by this system are intended solely for informational purposes. They are not intended to substitute professional medical advice, diagnosis, or treatment.',

    StringLocalization.cNoMedTitle: 'Not Medical Advice:',
    StringLocalization.cNoMedData:
        'All data and estimations should NOT be considered medical advice. This system does not provide medical diagnoses or treatment recommendations.',

    StringLocalization.cConsultTitle: 'Consultation with a Medical Professional:',
    StringLocalization.cConsultData:
        'Users must always consult with their medical professional or healthcare provider before making any health-related decisions based on the information provided by this system.',

    StringLocalization.cNoSubTitle: 'Not a Substitute for Professional Healthcare:',
    StringLocalization.cNoSubData:
        'This system is not a substitute for professional healthcare services. Users should never disregard professional medical advice or delay seeking it because of information obtained through this system.',

    StringLocalization.cIndividualTitle: 'Individual Variations:',
    StringLocalization.cIndividualData:
        "Individual health conditions and responses to health interventions can vary. The estimations provided by this system may not accurately represent an individual's specific health status.",

    StringLocalization.consentEnd:
        'You acknowledge that you have read, understood, and agreed to these terms. If you do not agree, please refrain from using the system. Always prioritize your health and seek guidance from qualified medical professionals for personalized advice.\n\nBy using this non-invasive',

    StringLocalization.cCheckMessage: 'I have read and understood and consent to the disclaimer provided above.',
    StringLocalization.accept: 'Accept',
    StringLocalization.decline: 'Decline',

    ///

    StringLocalization.imageLogin: 'asset/Help/logIn.jpg',
    StringLocalization.imageSignUp: 'asset/Help/signup.jpg',
    StringLocalization.imageResetPassword: 'asset/Help/resetPassword.jpg',
    StringLocalization.imageDashboard: 'asset/Help/home.jpg',
    StringLocalization.imageProfile: 'asset/Help/profile.jpg',
    StringLocalization.imageConnection: 'asset/Help/connectionScreen.jpg',
    StringLocalization.imageSetting: 'asset/Help/settings.jpg',
    StringLocalization.imageActivityDay: 'asset/Help/activityDay.jpg',
    StringLocalization.imageActivityWeek: 'asset/Help/activityWeek.jpg',
    StringLocalization.imageSleep: 'asset/Help/sleep.jpg',
    StringLocalization.imageTag: 'asset/Help/tagList.jpg',
    StringLocalization.imageTagEditor: 'asset/Help/tagEditor.jpg',
    StringLocalization.imageTagUpdate: 'asset/Help/tagUpdate.jpg',
    StringLocalization.imageGraph: 'asset/Help/graph.jpg',
    StringLocalization.imageMeasurementHistory: 'asset/Help/measurementHistory.jpg',
    StringLocalization.imageTagHistory: 'asset/Help/tagHistory.jpg',
    StringLocalization.imageDeviceManagement: 'asset/Help/deviceManagement.jpg',
    StringLocalization.imageFindBracelet: 'asset/Help/findBracelet.jpg',
    StringLocalization.imageTraining: 'asset/Help/training.jpg',
    StringLocalization.imageWearingMethod: 'asset/Help/wearingMethod.jpg',
    StringLocalization.imageWearingMethod2: 'asset/Help/wearing_method.png',
    StringLocalization.imageHourlyHR: 'asset/Help/hourlyHR.jpg',
    StringLocalization.imageBrightenScreen: 'asset/Help/brightenScreen.jpg',
    StringLocalization.imageBrightenScreen2: 'asset/Help/brighten_screen.png',
    StringLocalization.imageDoNotDisturb: 'asset/Help/doNotDisturb.jpg',
    StringLocalization.imageDoNotDisturb2: 'asset/Help/do_not_disturb.png',
    StringLocalization.imageTimeFormat: 'asset/Help/timeFormat.jpg',
    StringLocalization.imageMeasurement: 'asset/Help/measurementScreen.jpg',
  };
}
