// ignore_for_file: avoid_classes_with_only_static_members

import 'string_localization.dart';

/// Added by: Akhil
/// Added on: May/28/2020
/// This class contains all the Strings which are used in app in French Language

class FrenchLocalization {
  static Map<String, String> getLocalization = {
    StringLocalization.appName: 'HealthGauge',
    StringLocalization.dashBoardName: 'HealthGauge',
    StringLocalization.cnctnScreen: 'Connexion',
    StringLocalization.settingScreen: 'Réglages',
    StringLocalization.targetScreen: 'Objectif de Pas',
    StringLocalization.tagHistory: 'Étiquettes Historique',
    StringLocalization.sleeptargetScreen: 'Objectif de Someille',
    StringLocalization.btnTitle: 'Titre de Bouton',
    StringLocalization.btnTag: 'AJOUTER UNE ÉTIQUETTE',
    StringLocalization.btnTagU: 'MISE À JOUR UNE ÉTIQUETTE',
    StringLocalization.displayOne: 'AFFICHER UN',
    StringLocalization.tagScreen: 'Étiquette',
    StringLocalization.tagScreenSlctn: 'Sélection des Étiquette ',
    StringLocalization.headline: 'Entête',
    StringLocalization.subHeadline: 'Sous-Entête',
    StringLocalization.title: 'Titre',
    StringLocalization.subTitle: 'Sous Titre',
    StringLocalization.body2: 'Corps2',
    StringLocalization.body1: 'Corps1',
    StringLocalization.small: 'Petit',
    StringLocalization.caption: 'Légende',
    StringLocalization.appbarMgmt: 'Gestion d’Appareils',
    StringLocalization.monitor: 'CONNECTER L’APPAREIL',
    StringLocalization.timeFormat: 'Présentation du Temps',
    StringLocalization.timeF: '24h',
    StringLocalization.timeFo: '12h',
    StringLocalization.reset: 'Réinitialiser',
    StringLocalization.hrMonitor: 'Moniteur de Fréquence',
    StringLocalization.bScreen: 'Lèver le poignet pour éclairer l’écran',
    StringLocalization.dNd: 'Ne Pas Déranger',
    StringLocalization.firmUpdate: 'Mises à Jour de Firmware',
    StringLocalization.noInternet: 'Oups!',
    StringLocalization.enableInternet:
        'Il semble que vous n’êtes pas connectés à l’internet.  Activer votre connexion de données.',
    StringLocalization.retry: 'Réessayer',
    StringLocalization.cncl: 'Annuler',
    StringLocalization.mileage: 'Kilométrage',
    StringLocalization.kCal: 'Kcal',
    StringLocalization.comp: 'Achèvement',
    StringLocalization.hintForUserId: 'Nom d’Utilisateur',
    StringLocalization.hintForPassword: 'Mot de Passe',
    StringLocalization.hintForNewPassword: 'Nouveau Mot de Passe',
    StringLocalization.loginBtn: 'S’Identifier',
    StringLocalization.type: 'Type',
    StringLocalization.stps: 'Pas Effectués',
    StringLocalization.value: 'Valeur',
    StringLocalization.time: 'Temps',
    StringLocalization.date: 'Date',
    StringLocalization.notes: 'Notes',
    StringLocalization.day: 'Jour',
    StringLocalization.week: 'Semaine',
    StringLocalization.month: 'Mois',
    StringLocalization.timeH: 'Temps',
    StringLocalization.typeH: 'Type',
    StringLocalization.valueH: 'Valeur',
    StringLocalization.noteH: 'Note',
    StringLocalization.weekH: 'Cette Semaine',
    StringLocalization.lastH: 'Semaine Dernière',
    StringLocalization.skipBtn: 'Sauter',
    StringLocalization.btnForgotPassword: 'Mot de Passe Oublié?',
    StringLocalization.btnForgotUserId: 'Forgot UserId?',
    StringLocalization.next: 'Prochain',
    StringLocalization.dontHaveAnAccount: 'N’avez Pas de Compte?',
    StringLocalization.btnSignUp: 'S\'inscrire',
    StringLocalization.btnConnect: 'Connecter',
    StringLocalization.btnDisConnect: 'Déconnecter',
    StringLocalization.emptyUserId: 'Saisir le Nom d’Utilisateur',
    StringLocalization.emptyPassword: 'Saisir le Mot de Passe',
    StringLocalization.emptyNewPassword: 'Saisir le Nouveau Mot de Passe',
    StringLocalization.btnLogout: 'Quitter',
    StringLocalization.hintForEmail: 'Adresse Email',
    StringLocalization.emptyEmail: 'Saisir l’Adresse Email',
    StringLocalization.enterValidEmail: 'Saisir l’Adresse Email',
    StringLocalization.hintForFirstName: 'Prénom',
    StringLocalization.emptyFirstName: 'Saisir votre Prénom',
    StringLocalization.hintForLastName: 'Nom de Famille',
    StringLocalization.emptyLastName: 'Saisir votre Nom de Famille',
    StringLocalization.hintForBirthDate: 'Date de Naissance',
    StringLocalization.emptyBirthDate: 'Saisir votre Date de Naissance',
    StringLocalization.hintForPhone: 'Numéro de Téléphone',
    StringLocalization.emptyPhone: 'Saisir votre Numéro de Téléphone',
    StringLocalization.enterValidPhone: 'Saisir votre Numéro de Téléphone Valide',
    StringLocalization.confirmPasswordDoesntMatch:
        'Confirmer que le Mot de Passe ne Correspond pas',
    StringLocalization.hintForConfirmPassword: 'Confirmer le Mot de Passe',
    StringLocalization.emptyConfirmPassword: 'Mot de Passe',
    StringLocalization.termsAndConditions: 'Termes et Conditions d’Utilisation',
    StringLocalization.readMore: 'En Savoir Plus',
    StringLocalization.agreeTermsAndCondition: 'Veuillez accepter les Termes et Conditions',
    StringLocalization.save: 'Sauvegarder',
    StringLocalization.profile: 'Profil',
    StringLocalization.pleaseLoginFirstToUseThisFeature:
        'Veuillez vous connecter d’abord pour ultiliser cette fonction.',
    StringLocalization.cancel: 'Annuler',
    StringLocalization.ok: 'D\'accord',
    StringLocalization.deviceBattery: 'Batterie de l’Appareil',
    StringLocalization.bp: 'Tension Artérielle',
    StringLocalization.offLineEcgSbp: '0/0',
    StringLocalization.heartRate: 'Rhythme Cardiaque',
    StringLocalization.hrv: 'Variabilité Cardiaque',
    StringLocalization.health: 'Santé',
    StringLocalization.symptoms: 'symptômes',
    StringLocalization.complete: 'Compléter',
    StringLocalization.steps: 'Pas Effectués',
    StringLocalization.calories: 'Calories',
    StringLocalization.kml: 'kcal',
    StringLocalization.zeroKml: 'kml',
    StringLocalization.distance: 'Distance',
    StringLocalization.km: 'Km',
    StringLocalization.zeroKm: '0 km',
    StringLocalization.activity: 'Activité',
    StringLocalization.sleepS: 'Someille',
    StringLocalization.sleepHour: 'Heure(s) de Someil',
    StringLocalization.hour: 'Heure',
    StringLocalization.sleep: 'Someille',
    StringLocalization.disconnect: 'Déconnecter!',
    StringLocalization.areYouSureWantToDisconnect: 'Êtes-vous sûr que vous vouliez déconnecter',
    StringLocalization.connectedDevice: 'Appareil Connecté',
    StringLocalization.connected: 'Connecté',
    StringLocalization.disconnected: 'Déconnecté',
    StringLocalization.andConnect: 'et connectez',
    StringLocalization.gender: 'Sexe',
    StringLocalization.male: 'H',
    StringLocalization.female: 'F',
    StringLocalization.others: 'A',
    StringLocalization.unit: 'Unité',
    StringLocalization.metric: 'Métrique',
    StringLocalization.imperial: 'Impérial',
    StringLocalization.dateOfBirth: 'Date de Naissance',
    StringLocalization.selectBirthDate: 'Choisir la Date de Naissance',
    StringLocalization.height: 'Taille',
    StringLocalization.confirm: 'Confirmer',
    StringLocalization.feet: 'Pieds',
    StringLocalization.inch: 'Pouces',
    StringLocalization.skinPhotoType: 'Phototype de la Peau',
    StringLocalization.width: 'Largeur',
    StringLocalization.lb: 'Livre',
    StringLocalization.measurement: 'Mesure or Prise de Mesure',
    StringLocalization.startMeasurement: 'Lance la Mesure',
    StringLocalization.training: 'Formation',
    StringLocalization.synchronization: 'Synchronisation',
    StringLocalization.hrBPM: 'Rhythme Cardiaque (bpm)',
    StringLocalization.bpMmHg: 'Tension Artérielle',
    StringLocalization.bplegend:
        'Les données présentées sont à titre indicatif et ne sont pas considérées comme des données médicales.',
    StringLocalization.countDown: 'Compte à Rebours: ',
    StringLocalization.ecg: 'ECG',
    StringLocalization.ppg: 'PPG',
    StringLocalization.calibration: 'Étalonnage',
    StringLocalization.hr: 'Rhythme Cardiaque',
    StringLocalization.sbd: 'Tension Artérielle Systolique',
    StringLocalization.dbp: 'Tension Artérielle Diastolique',
    StringLocalization.shortDescription:
        'Veuillez entrer/saisissez les résultates de votre appareil oscillométrique',
    StringLocalization.add: 'AJOUTER',
    StringLocalization.addToGraph: 'AJOUTER AU GRAPHIQUE',
    StringLocalization.measurementHistory: 'Mesures Historiques',
    StringLocalization.today: 'Aujourd’hui',
    StringLocalization.yesterday: 'Hier',
    StringLocalization.tomorrow: 'Demain',
    StringLocalization.stopMeasurement: 'Arrêter la Mesure',
    StringLocalization.edit: 'Éditer',
    StringLocalization.camera: 'Prendre une Photo',
    StringLocalization.gallery: 'Choisir du téléphone',
    StringLocalization.remove: 'Enlever',
    StringLocalization.min: 'Min',
    StringLocalization.max: 'Max',
    StringLocalization.enterMin: 'Saisir le Min',
    StringLocalization.minMustBeSmallerThenMax: 'Valeur Invalide',
    StringLocalization.enterMax: 'Saisir le Max',
    StringLocalization.minMustBeSmallerThenMin: 'Valeur Invalide',
    StringLocalization.label: 'Label d\'Étiquette',
    StringLocalization.enterLabel: 'Saisir le Label d\'Étiquette',
    StringLocalization.defaultValue: 'Saisir la Valeur',
    StringLocalization.enterBetween: 'Saisir Entre',
    StringLocalization.digit: 'Chiffre',
    StringLocalization.enterDigit: 'Saisir le Chiffre',
    StringLocalization.centimetre: 'Centimètre',
    StringLocalization.kg: 'kg',
    StringLocalization.weight: 'Poids',
    StringLocalization.updatedSuccessfully: 'Mise à Jour avec Succès',
    StringLocalization.failToUpdate: 'Mise à Jour a Échouée',
    StringLocalization.sleepHistoryTitle: 'Someille',
    StringLocalization.chooseYourStepTarget: 'Choisir votre objectif de pas',
    StringLocalization.stepSuggestion: 'Suggérer 8000 ~ 10000 pas chaque jour',
    StringLocalization.chooseSleepTarget: 'Choisir votre objectif de someille',
    StringLocalization.sleepSuggestion: 'Suggestion que les adults dorment 7 - 9 heures par jour',
    StringLocalization.noDataFound: 'Aucun Donnée Trouvée',
    StringLocalization.stayUp: 'Rester Debout',
    StringLocalization.light: 'Lumière',
    StringLocalization.deep: 'Profond',
    StringLocalization.commingSoon: 'Bientôt Disponible',
    StringLocalization.target: 'Objectif',
    StringLocalization.minute: 'Minute',
    StringLocalization.privacyPolicy: 'Politique de Confidentialité',
    StringLocalization.tagLabelEditor: 'TÉditeur de Label d\'Étiquette',
    StringLocalization.addTagTitle: 'Ajouter un nouveau étiquette',
    StringLocalization.update: 'Mise à Jour',
    StringLocalization.selectTag: 'Étiquette Sélectionnée',
    StringLocalization.range: 'Éventail',
    StringLocalization.minimum: 'Minimum',
    StringLocalization.maximum: 'Maximum',
    StringLocalization.defaultValueTag: 'Valeur par Défaut: ',
    StringLocalization.precision: 'Précision',
    StringLocalization.tag: 'Étiquette',
    StringLocalization.tagValue: 'Valeur: ',
    StringLocalization.change: 'Changement',
    StringLocalization.addNote: 'Ajouter une Étiquette',
    StringLocalization.updateNote: 'Mise à Jour une Étiquette',
    StringLocalization.enterUnit: 'Saisir l’Unité',
    StringLocalization.stress: 'Stress',
    StringLocalization.number: 'Nombre',
    StringLocalization.fatigue: 'Fatigue',
    StringLocalization.bloodGlucose: 'Glucose Sanguin',
    StringLocalization.exercise: 'Exercise',
    StringLocalization.bodyTemperature: 'Température',
    StringLocalization.celsius: 'Celsius',
    StringLocalization.breathing: 'Respiration',
    StringLocalization.deviceManagement: 'Gestion des Appareils',
    StringLocalization.hourlyHrMonitor: 'Rhythme Cardiaque Horaire',
    StringLocalization.liftTheWristBrighten: 'Lèver Le Poignet Pour Éclairer L’Écran',
    StringLocalization.doNotDisturb: 'Ne Pas Déranger',
    StringLocalization.twelve: '12h',
    StringLocalization.twentyFour: '24h',
    StringLocalization.wearType: 'Méthode de Port',
    StringLocalization.leftHand: 'Gauche',
    StringLocalization.rightHand: 'Droit',
    StringLocalization.graph: 'Graphique',
    StringLocalization.selectItem: 'Sélectionnez Élément',
    StringLocalization.somethingWentWrong: 'Quelque chose a mal tourné',
    StringLocalization.oops: 'Oups!',
    StringLocalization.unknown: 'Inconnu',
    StringLocalization.healthGauge: 'HealthGauge',
    StringLocalization.helpForMeasurement: 'Mesure',
    StringLocalization.help: 'Aide',
    StringLocalization.findBracelet: 'Trouver l’appareil',
    StringLocalization.version: 'Version',
    StringLocalization.selectLanguage: 'Langue',
    StringLocalization.overrideLanguageSetting: 'Remplacer les Paramètres de Langage',
    StringLocalization.localization: 'Localisation',
    StringLocalization.chooseSelectedLanguage: 'Activer pour changer de/la langue',
    StringLocalization.english: 'Anglais (e)',
    StringLocalization.hindi: 'Hindi',
    StringLocalization.french: 'French',
    StringLocalization.spanish: 'Spanish',

    StringLocalization.ppgNoChartDataAvailable: 'Aucunne donnees de tableau est accessible',
    StringLocalization.enterTitle: 'Entrer le Titre',
    StringLocalization.kSearchMailHint: 'Chercher votre Email',
    StringLocalization.kInbox: 'Boîte de Réception',
    StringLocalization.kDrafts: 'Brouillon',
    StringLocalization.kTrash: 'Poubelle',
    StringLocalization.kSent: 'Envoyer',
    StringLocalization.appReminders: 'Rappel de l’Application',
    StringLocalization.reminders: 'Rappels',
    StringLocalization.addReminders: 'Ajouter des Rappels',
    StringLocalization.updateReminders: 'Rappels de Mise à Jour',
    StringLocalization.call: 'Appel',
    StringLocalization.language: 'Language',
    StringLocalization.message: 'Message',
    StringLocalization.qq: 'QQ',
    StringLocalization.weChat: 'WeChat',
    StringLocalization.linkedIn: 'LinkedIn',
    StringLocalization.skype: 'Skype',
    StringLocalization.facebookMessenger: 'Facebook Messanger',
    StringLocalization.twitter: 'Twitter',
    StringLocalization.whatsApp: 'WhatsApp',
    StringLocalization.viber: 'Viber',
    StringLocalization.line: 'Ligne',
    StringLocalization.kOutBox: 'Boîte d’Envoi',

    StringLocalization.startTime: 'Heure de Début',
    StringLocalization.endTime: 'Heure de Fin',
    StringLocalization.intervalTime: 'Intervalles de Temps',
    StringLocalization.repeat: 'Répéter',
    StringLocalization.description: 'Description',
    StringLocalization.sun: 'D',
    StringLocalization.mon: 'L',
    StringLocalization.tue: 'M',
    StringLocalization.wed: 'M',
    StringLocalization.thu: 'J',
    StringLocalization.fri: 'V',
    StringLocalization.sat: 'S',
    StringLocalization.selectImage: 'Sélectionnez l’Image',
    StringLocalization.notification: 'Notification',
    StringLocalization.waterReminderTitle: 'Hydratation',
    StringLocalization.dontForgetToDrinkWater: 'N’oubliez pas de boire de l’eau',
    StringLocalization.sedentaryReminderTitle: 'Sédentaire',
    StringLocalization.sedentaryDesc: 'C’est le temps de se léver',
    StringLocalization.medicineReminderTitle: 'Médicament',
    StringLocalization.medicineDesc: 'Prenez vos médicaments',
    StringLocalization.leadOff: 'Lead Off',
    StringLocalization.leadDesc:
        "Veuillez mettre l'index de votre main opposée au bas du bracelet.",
    StringLocalization.poorConductive: 'Pauvre conducteur',
    StringLocalization.poorConductiveDesc:
        'il est recommandé de tester \n l\'eau au contact du capteur.',
    StringLocalization.goodSignal: 'Bon Mesure',
    StringLocalization.readyForMeasurement: 'Prêt pour la mesure?',
    StringLocalization.measurementInProgress: 'Mesure en cours.',

    StringLocalization.holdHand:
        '1. Tenez toujours votre main.\n2. Le bracelet doit être bien ajusté.\n3. Veuillez mettre le doigt d\'index de votre main opposée sur le bas du bracelet.\n4. Il est recommandé d\'humidifier votre peau dans la zone de contact avec le bracelet.',
    StringLocalization.braceletSung: '2) Le bracelet doit être bien ajusté.',
    StringLocalization.putYourFinger:
        '3) Veuillez mettre le doigt d\'index de votre main opposée sur le bas du bracelet.',
    StringLocalization.recommodateMoisten:
        '4) Il est recommandé d\'humidifier votre peau dans la zone de contact avec le bracelet.',
    StringLocalization.doNotAskAgain: 'Ne me demandez plus',
    StringLocalization.diet: 'Diet',
    StringLocalization.medicine: 'Médecine',
    StringLocalization.corona: 'Covid-19',
    StringLocalization.smoking: 'Smoking',
    StringLocalization.alcohol: 'Alcohol',
    StringLocalization.glucosepatch: 'Glucose Patch',
    StringLocalization.glucosepatchlocation: 'GlucoseEmplacement du Patch de Glucose',

    StringLocalization.allowance: 'Allowance',
    StringLocalization.search: 'Rechercher',
    StringLocalization.more: 'Plus',
    StringLocalization.MMOLPerLiter: 'mmol/L',
    StringLocalization.MMGL: 'mg/dL',
    StringLocalization.measurementResult: 'Résultat de mesure',
    StringLocalization.measurementData: 'Votre estimation de la pression artérielle est:',
    StringLocalization.estimating: 'Estimation',
    StringLocalization.contacts: 'Contacts',
    StringLocalization.delete: 'Supprimer',
    StringLocalization.contactDeleted: 'Contact supprimé',
    StringLocalization.noContactFound: 'Aucun contact trouvé !!!',
    StringLocalization.invitations: 'Des invitations',
    StringLocalization.searchContact: 'Recherche Contact',
    StringLocalization.searchUser: 'Recherchez un utilisateur',
    StringLocalization.noPendingInvitations: 'Aucune invitation en attente',
    StringLocalization.noPendingInvitationToSearchFrom:
        'Aucune invitation à effectuer une recherche depuis',
    StringLocalization.addContacts: 'Ajouter des contacts',
    StringLocalization.invitedSucessfully: 'Invité avec succès',
    StringLocalization.invitationFailed: "Échec de l'invitation",
    StringLocalization.searchNameOfUser: "Rechercher le nom de l'utilisateur",
    StringLocalization.nothingToShow: 'Rien à montrer',
    StringLocalization.pageDeleted: 'Page supprimée',
    StringLocalization.pageAdded: 'Page ajoutée',
    StringLocalization.youCanNotAddMorePages: 'Vous ne pouvez pas ajouter plus de pages',
    StringLocalization.addPage: 'Ajouter une page',
    StringLocalization.deleteCurrentPage: 'Supprimer la page actuelle',
    StringLocalization.editTitleOfpage: 'Modifier le titre de la page',
    StringLocalization.addTitleOfpage: 'Add le titre de la page',
    StringLocalization.editTitle: 'Modifier le titre',
    StringLocalization.compose: 'Composer',
    StringLocalization.to: 'À',
    StringLocalization.cc: 'CC',
    StringLocalization.subject: 'Sujet',
    StringLocalization.body: 'Composer un courriel',
    StringLocalization.enterAllFields: 'Entrez tous les champs',
    StringLocalization.pleaseEnterToSubject: 'Veuillez sélectionner un contact et saisir un sujet',
    StringLocalization.addToDrafts: 'Ajouter aux brouillons',
    StringLocalization.draftConfirmation:
        'En cliquant sur D\'accord, vous confirmez enregistrer le courrier dans les brouillons',
    StringLocalization.messageSentSuccessfully: 'Message envoyé avec succès',
    StringLocalization.messageNotSent: 'Message non envoyé',
    StringLocalization.untrash: 'Restaurer',
    StringLocalization.emailDeletedSuccessfully: "L'e-mail a bien été supprimé",
    StringLocalization.selectAll: 'Sélectionner tout',
    StringLocalization.emailRestoredSuccessfully: 'E-mail restauré avec succès',
    StringLocalization.detail: 'Détail',
    StringLocalization.from: 'De',
    StringLocalization.reply: 'Répondre',
    StringLocalization.replyAll: 'Répondre à tous',
    StringLocalization.forward: 'En avant',
    StringLocalization.requested: 'Demandé',
    StringLocalization.helpPageUrl: 'asset/help_french.html',
    StringLocalization.healthKit: 'Kit Santé',
    StringLocalization.googleFit: 'Google Fit',
    StringLocalization.alarm: 'Alarme',
    StringLocalization.addAlarm: 'Ajouter une alarme',
    StringLocalization.selectDays: 'Sélectionner des jours',
    StringLocalization.alarmLabel: "Étiquette d'alarme",
    StringLocalization.selectTime: "Sélectionnez l'heure",
    StringLocalization.addNameForBluetoothDevice: 'Nommez cet appareil',
    StringLocalization.enterName: 'cacher',
    StringLocalization.hideFromList: "Masquer l'appareil dans la liste",
    StringLocalization.showAll: 'Afficher tout',
    StringLocalization.hide: 'Cacher',
    StringLocalization.allSleep: 'Sommeil',
    StringLocalization.deepSleep: 'Sommeil profond',
    StringLocalization.lightSleep: 'Sommeil léger',
    StringLocalization.autoLoad: 'Chargement automatique',
    StringLocalization.autoTagging: 'Étiquetage automatique',
    StringLocalization.termsAndConditionPageUrl: 'asset/terms_and_condition_french.html',

    StringLocalization.systolic: 'Sys',
    StringLocalization.diastolic: 'Dia',
    StringLocalization.goal: 'Objectif',
    StringLocalization.awake: 'Éveillé',
    StringLocalization.chooseYourCaloriesTarget: 'Choisir votre but de calories',
    StringLocalization.caloriesSuggestion:
        'Sujestion: femmes 1600 ~ 2400 calories par jour et les hommes 2000 ~ 3000 calories par jour.',
    StringLocalization.caloriesTarget: 'But de calories:',
    StringLocalization.chooseYourDistanceTarget: 'Choisir votre but de distance',
    StringLocalization.distanceTarget: 'But de distance:',
    StringLocalization.distanceSuggestion: 'Sujestion: 5 ~ 7 km par jour',
    StringLocalization.normal: 'ORDINAIRE',
    StringLocalization.resting: 'Repos',
    StringLocalization.walking: 'Marche',
    StringLocalization.exercising: 'Excercise',
    StringLocalization.slow: 'Lent',
    StringLocalization.fast: 'Vite',
    StringLocalization.whatStateAreYouMeasuringIn: 'Dans quel état mesurez-vous?',
    StringLocalization.maxEffort: 'Effort maximale',
    StringLocalization.hardCoreTraining: 'Entraînement intense',
    StringLocalization.enduranceTraining: 'Entraînement en endurance',
    StringLocalization.fatBurning: 'Brûler les graisses',
    StringLocalization.normalization: 'Normalization',
    StringLocalization.weightMeasurement: 'Measure du poids',
    StringLocalization.measuringKeepStanding: 'Rester debout pour la measurement',
    StringLocalization.unStableWeight: 'Fluctuations du poids',
    StringLocalization.onBoardNow: 'Veuilliez montez la balance maintenant',
    StringLocalization.measureComplete: 'Measure est terminée',
    StringLocalization.allMeasurementNotTaken: 'Measurement incomplet',
    StringLocalization.withinADay: 'Durant une journée',
    StringLocalization.deviceNotConnected: 'L’appareil n’est past connecté',
    StringLocalization.overweight: 'SURPOIDS',
    StringLocalization.underweight: 'INSUFFISANT',
    StringLocalization.normalWeight: 'ORDINAIRE',
    StringLocalization.ideal: 'Idéal',
    StringLocalization.thin: 'Mince',
    StringLocalization.obese: 'OBÉSÉ',
    StringLocalization.low: 'BAS',
    StringLocalization.preHyper: 'PRÉ',
    StringLocalization.hyper: 'HYPER',
    StringLocalization.high: 'haut',
    StringLocalization.alert: 'alerte',
    StringLocalization.danger: 'Danger',
    StringLocalization.excellent: 'Excellent',
    StringLocalization.bMI: 'BMI',
    StringLocalization.bfr: 'Ratio de graisse corporelle',
    StringLocalization.muscleRate: 'Taux de muscle',
    StringLocalization.bodyWater: 'Eau corporelle',
    StringLocalization.visceralFatIndex: 'Indice de graisse viscérale',
    StringLocalization.bmr: 'BMR',
    StringLocalization.proteinRate: 'Taux de protéines',
    StringLocalization.boneMass: 'Masse osseuse',
    StringLocalization.avgOfDay: 'Moyenne de la journée',
    StringLocalization.avgOfWeek: 'Moyenne de la semaine',
    StringLocalization.avgOfMonth: 'Moyenne du mois',
    StringLocalization.bodyMassIndex: 'Indice de masse corporelle',
    StringLocalization.oscillometric: "Vérification de l'IA oscillométrique",
    StringLocalization.tab: 'Onglet',
    StringLocalization.editTitleOfGraph: 'Modifier le titre du graphique',
    StringLocalization.startDate: 'date de début',
    StringLocalization.addWeightDescription: 'veuillez entrer votre poids',
    StringLocalization.selectUnit: 'Veuillez choisir un unité',
    StringLocalization.researcherProfile: 'Profil de \nchercheur',
    StringLocalization.researcherProfileTitle: 'Profil de chercheur',
    StringLocalization.enterPassword: 'Entrez le mot de passe',
    StringLocalization.enterPasswordText: 'Entrez le mot de passe pour devenir un chercheur',
    StringLocalization.wrongPassword: 'Mot de passe incorrect',
    StringLocalization.youAreResearcher: 'Vous êtes maintenant un chercheur',
    StringLocalization.heartRateShortForm: 'HR',
    StringLocalization.notResearcher: "Vous n'êtes plus un chercheur",
    StringLocalization.Ai: 'IA',
    StringLocalization.sleepData: 'Données de sommeil',
    StringLocalization.wrongData: 'Mesure arrêtée!',
    StringLocalization.wrongDataDescription:
        'Données de mesure sont incorrectes, voulez-vous relancer la mesure?',
    StringLocalization.restart: 'Relancer',

    ///Added by: Shahzad
    ///Added on: 28/10/2020
    ///Contains string localisation for help page
    StringLocalization.HGOverview: 'Aperçu de Health Gauge',
    StringLocalization.HGIntro:
        'Health Gauge est une platforme pour la mesure et la gestion de la santé personelle. Les utilisateurs de la platforme incluent le grand public qui s’intéresse à la santé et au bien-être, les prestataires de soins qui travaillent avec les utilisateurs, les chercheurs qui accèdent aux données afin de développer et de fournir des analyses, et les partenaires commerciales qui founissent des biens et des services à la communauté des utilisateurs de HealthGauge.  La platforme accepte des connexions de divers appareils de santé et de portables de fitness; toutefois, les utilisateurs peuvent utiliser HealthGauge sans appareil pour mesurer et gérer leur santé et travailler avec leurs équipe de soins même s’ils n’ont pas d’appareil de santé.  Les composantes de l’application mobile de HealthGauge sont les suivantes:',
    StringLocalization.login: 'Se Connecter',
    StringLocalization.loginInfo:
        'Ici, vous pouvez ouvrir une session dans l’application.  Lorsque vous vous connectez à l’application HealthGauge, vous restez connecté jusqu’à ce que vous vous déconnectiez ou arrêtiez l’application.',
    StringLocalization.signUp: 'Inscription',
    StringLocalization.signUpInfo:
        'Vous pouvez utiliser la page d’inscription pour vous inscrire à un compte.  Une fois que votre compte créé, vos informations de profil pour le compte sont stockées localement, mais synchronisées avec le serveur HealthGauge.  Notez que vous pouvez toujours utiliser l’application sans compte, mais aucune de vos données ne sera sauvegardé.',
    StringLocalization.resetPassword: 'Réinitialiser le mot de passe',
    StringLocalization.resetPasswordInfo:
        'Vous pouvez demander une réinitialisation du mot de passe à partir de la page de connexion principale.',
    StringLocalization.home: 'La Page d’Accueil',
    StringLocalization.homeInfo:
        'Depuis la page d’accueil, vous pouvez accéder aux fonctions de base en utilisant les menus du haut et du bas.  Depuis le menu du haut, vous pouvez naviguer vers les pages Profil, Connexion et Paramètres.Le menu du bas reste visible pour la plupart des activités et peut être utilisé pour accéder aux pages Accueil, Graphique, Mesure, Balise et Aide.Dans la partie principale de la page d’accueil, vous verrez un aperçu de vos paramètres de santé pour la journée. Cette section comprend des statistiques sur la santé dans trois groupes, y compris les mesures cardio, les activités et le sommeil.Voir ci-dessous pour plus de détails sur chaque page.',
    StringLocalization.HGProfile: 'Profil',
    StringLocalization.profileInfo:
        'Vous pouvez remplir votre page Profil avec votre photo, votre nom, votre identité, votre date de naissance, votre taille, votre poids, votre sexe et la couleur de votre peau. Ces facteurs peuvent avoir une incidence sur la luminosité des capteurs portables nécessaires pour relever vos mesures de santé les plus précis. Il est donc essentiel pour le système d’intelligence artificielle que toutes les données saisies soient exactes. Soyez assuré que vos données sont privées et sécurisées sur notre serveur web.',
    StringLocalization.HGConnection: 'Connexion',
    StringLocalization.connectionInfo:
        'La page Connexions répertorie les périphériques Bluetooth (BLE) disponibles. Chaque appareil est associé à un identifiant qui apparaîtra automatiquement sur votre page Connexions. Pour vous connecter à un appareil (comme votre portable de santé), sélectionnez simplement le bon appareil et appuyez sur « Connecter ».  Après avoir connecté un appareil, l’appareil restera connecté en permanence et se reconnectera automatiquement si la connexion est perdue.',
    StringLocalization.HGSettings: 'Réglages',
    StringLocalization.settingsInfo:
        'Ici vous pouvez accéder aux fonctions de gestion des appareils, aux termes et conditions et voir le numéro de version. Si vous perdez votre portable, vous pouvez également le localiser en utilisant la fonction Trouver bracelet.  De la page Paramètres, vous pouvez définir des objectifs d’activité et de sommeil, et voir vos mesures historiques pour l’activité, le sommeil, cardio et tags. Si vous souhaitez modifier les activités que vous étiquetez (comme l’alimentation, le tabagisme ou le stress), vous pouvez modifier vos balises à partir de vos paramètres.',
    StringLocalization.cardioMeasurement: 'Mesure Cardio',
    StringLocalization.cardioMeasurementInfo:
        'La page de Mesure Cardio vous permet de prendre une mesure cardio qui comprend l’électrocardiogramme, le photopléthysmogramme, la fréquence cardiaque et la variabilité de la fréquence cardiaque.  Ces données sont utilisées pour estimer votre tension artérielle systolique et diastolique.  Vos indicateurs de santé sont stockés dans votre appareil et synchronisés sur notre serveur Web sécurisé lorsque vous avez accès à Internet.',
    StringLocalization.activityDay: 'Activité Quotidienne',
    StringLocalization.activityDayInfo:
        'HealthGauge suit le nombre de pas quotidiens. En fonction de votre profil et du nombre de calories brûlées, votre distance parcourue en une journée est estimée.  Vous pouvez voir vos niveaux d’activité dans une vue sommaire par jour, semaine, ou mois. Vos données d’activité est stockées dans votre appareil et synchronisées sur notre serveur Web sécurisé lorsque vous avez accès à l’internet.',
    StringLocalization.activityWeeklyMonthly: 'Sommaire hebdomadaire et mensuel des activités',
    StringLocalization.activityWeeklyMonthlyInfo:
        'Vos données sur les activités sont résumées sur un graphique qui montre vos niveaux d’activité au fil du temps.  À partir de la page Activité, vous pouvez sélectionner une vue sommaire quotidienne, hebdomadaire ou mensuelle.',
    StringLocalization.HGSleep: 'Someille',
    StringLocalization.sleepInfo:
        'Pendant la nuit, le sommeil est suivi en fonction de votre mouvement.  Le portable mesure votre sommeil par incréments de 15 minutes et détecte si vous êtes éveillé, dans un sommeil léger, ou dans un sommeil profond.  À partir de la page de Sommeil, un tableau de couleur montre le temps que vous avez passé à chaque niveau de sommeil (par incréments de 15 minutes).  Lorsque vous consultez votre graphique, vous pouvez sélectionner une vue sommaire quotidienne, hebdomadaire ou mensuelle.  Vos données de sommeil est stockées dans votre appareil et synchronisées sur notre serveur Web sécurisé lorsque vous avez accès à Internet.',
    StringLocalization.HGTag: 'Étiquette',
    StringLocalization.tagInfo:
        'Vous pouvez marquer toutes les mesures que vous voulez à tout moment. Après votre activité, choisissez simplement l’une des 9 étiquettes par défaut, y compris l’alimentation, l’exercice, le stress, le tabagisme et plus encore. Si vous ne voyez pas d’étiquette pour votre activité, vous pouvez créer votre propre étiquette.Les étiquettes enregistrent un point d’intérêt dans votre journée afin que vous puissiez voir comment cette activité influe sur vos lectures de santé. En fonction de ce que vous avez choisi de surveiller, vous pouvez étiqueter votre température, fatigue, glycémie, habitudes alimentaires, médicaments et plus.',
    StringLocalization.tagEditorList: 'Modifier la Liste des Étiquettes',
    StringLocalization.tagEditorListInfo:
        'ette page apparaît dans la zone des paramètres.  Elle vous permet de créer ou de modifier des étiquette (voir la section 12.  Étiquette).  Le premier écran est une liste d’étiquettes à modifier.  Pour ajouter une nouvelle étiquette, cliquez sur « + » et entrez le nom et l’icône de l’étiquette. Noter: les étiquettes que vous sélectionnez sont synchronisées avec l’application Web et mobile.  Vous pouvez supprimer et ré-ajouter des étiquettes, créer de nouvelles étiquettes ou modifier des étiquettes existantes.',
    StringLocalization.tagEditor: "Éditeur d'Étiquette",
    StringLocalization.tagEditorInfo:
        'Ceci apparaît comme un fenêtre et vous permet de modifier les détails d’une étiquette.  Vous pouvez choisir le niveau de détail que vous voulez ajouter à une étiquette.  Vous pouvez indiquer le nom d’étiquette, l’unité de mesure, la zone de valeurs permise et le niveau de précision.  Vous pouvez également sélectionner une valeur par défaut si vous le souhaitez.',
    StringLocalization.HGGraph: 'Graphique',
    StringLocalization.graphInfo:
        'La page Tableau de Bord fournit un aperçu graphique de vos mesures de santé et de tout ce que vous choisissez de suivre. Les données peuvent être visualisées sous forme de résumé du jour, de la semaine et du mois. Bien que les graphiques de santé par défaut seront ajoutés pour vous, vous pouvez choisir de suivre plus de données en ajoutant un widget. Un widget est une collection de mesures sur une période de temps sélectionnée. Chaque widget affiché peut être modifié pour ajouter ou supprimer toute mesure ou baliser une valeur dans le système.',
    StringLocalization.HGMeasurementHistory: 'Mesures Historiques',
    StringLocalization.measurementHistoryInfo:
        'Cette option est disponible dans les paramètres.  Sur la page Historique des mesures, vous pouvez voir un résumé de vos mesures cardio sur une journée, une semaine ou un mois.',
    StringLocalization.HGTagHistory: 'Étiquettes Historique',
    StringLocalization.tagHistoryInfo:
        'Cette option est disponible dans les paramètres. À partir de la page Historique des étiquettes, vous pouvez voir vos attributions des étiquettes sur une journée, une semaine ou un mois.',
    StringLocalization.moreFunctions: 'Plus de Fonctions',
    StringLocalization.HGFindBracelet: 'Trouver l’appareil',
    StringLocalization.findBraceletInfo: 'Fonction simple pour faire vibrer l’appareil connecté.',
    StringLocalization.HGliftTheWristBrighten: 'Lèver Le Poignet Pour Éclairer L’Écran',
    StringLocalization.liftTheWristBrightenInfo:
        'Fonction simple qui éteindre ou activer la capacité de l’appareil de s’allumer lorsque l’appareil est soulevé.',
    StringLocalization.HGDoNotDisturb: 'Ne Pas Déranger',
    StringLocalization.doNotDisturbInfo: 'Option simple pour éteindre les vibrations la nuit.',
    StringLocalization.HGTimeFormat: 'Présentation du Temps',
    StringLocalization.timeFormatInfo:
        'L’heure peut être affichée sur l’appareil dans un format de 12 ou 24 heures.',
    StringLocalization.HGWearingMethod: 'Méthode de Port',
    StringLocalization.wearingMethodInfo:
        'Indique si l’appareil doit être porté de la main gauche ou de la main droite. La fonctionnalité est la même, mais l’ECG est inversé sur le poignet droit.',
    StringLocalization.HGTraining: 'Formation',
    StringLocalization.trainingInfo:
        'Il s’agit d’une option disponible dans la page des paramètres qui permet à l’utilisateur de saisir des données de formation. En entrant des données qui correspondent à leur profil, un utilisateur peut augmenter la précision des évaluations de la tension artérielle.',
    StringLocalization.HGhrMonitor: 'Moniteur de Fréquence',
    StringLocalization.hrMonitorInfo:
        'Cette option est disponible dans la page de gestion de l’appareil. Ce paramètre permet à l’appareil d’enregistrer des mesures horaires.',
    StringLocalization.references: 'References',

    StringLocalization.weightUrl:
        'https://www.nursingcenter.com/ncblog/august-2017/body-mass-index-and-body-surface-area-what-s-the-d',
    StringLocalization.bpUrl:
        'http://www.bloodpressureuk.org/your-blood-pressure/understanding-your-blood-pressure/what-do-the-numbers-mean/',
    StringLocalization.sleepUrl:
        'https://www.corvallisclinic.com/sleep-medicine/understanding-your-sleep-study/',
    StringLocalization.hrUrl:
        'https://myheart.net/articles/what-is-a-normal-heart-rate/#:~:text=What%20is%20a%20Normal%20or,than%20100%20beats%20per%20minute',
    StringLocalization.furtherInfoBp:
        'Pour de plus d\'informations sur la pression artérielle, consultez ce lien : ',
    StringLocalization.furtherInfoHr:
        "Pour plus d'informations sur la fréquence cardiaque, consultez ce lien : ",
    StringLocalization.furtherInfoWeight:
        "Pour plus d'informations sur le poids et IMC, consultez ce lien : ",
    StringLocalization.furtherInfoSleep:
        "Pour plus d'informations sur le sommeil, consultez ce lien : ",

    StringLocalization.maxWeight: 'Poids initial',

    StringLocalization.deleteGraph: 'Êtes-vous sûr de vouloir supprimer ce graphique ?',
    StringLocalization.no: 'Non',
    StringLocalization.yes: 'Oui',
    StringLocalization.selectColor: 'Sélectionnez une couleur',
    StringLocalization.MMOL: 'mmol/L',
    StringLocalization.MGDL: 'mg/dL',
    StringLocalization.fahrenheit: 'Fahrenheit',
    StringLocalization.glass: 'Verre',
    StringLocalization.running: 'Courir',
    StringLocalization.hiking: 'Randonnée',
    StringLocalization.biking: 'Vélo',
    StringLocalization.easy: 'Facile',
    StringLocalization.moderate: 'Modéré',
    StringLocalization.selectGraphType: 'Sélectionnez le type de graphique',
    StringLocalization.lineGraph: 'linéair',
    StringLocalization.barGraph: 'barres',
    StringLocalization.lineAndBarGraph: 'linéaire et à barres',
    StringLocalization.deviceData: 'Données de l’appareil',
    StringLocalization.result: 'Résultat',
    StringLocalization.AIData: "Données estimées d'IA",
    StringLocalization.userData: 'Données saisies par l’utilisateur',
    StringLocalization.aDayAgo: 'dernier jour',
    StringLocalization.daysAgo: 'Jours précédents',
    StringLocalization.endDate: 'Date de fin',

    StringLocalization.addGraphRestriction: 'Vous pouvez pas ajouter plus que deux types',
    StringLocalization.chooseYourWeightTarget: 'Choisir votre but de poids',
    StringLocalization.weightTarget: 'Objectif de Poids',
    StringLocalization.weightSuggestion: 'Suggestion: ',
    StringLocalization.meter: 'Meter',
    StringLocalization.titleSbp: 'Systolic BP',
    StringLocalization.changesNotSaved: 'Les modifications ne sont pas enregistrées',
    StringLocalization.notSavedDescription: 'Vous voulez sauvegarder vos modifications?',
    StringLocalization.initialWeightInfo:
        "C'est le poids de l'utilisateur au moment de l'installation de l'application",
    StringLocalization.hRNormal: 'Séance',
    StringLocalization.brightness: 'Luminosité',
    StringLocalization.Low: 'Bas',
    StringLocalization.Medium: 'Moyen',
    StringLocalization.High: 'Haut',
    StringLocalization.homeScreenItems: "Éléments de l'écran d'accueil",
    StringLocalization.bloodPressure: 'Tension Artérielle',
    StringLocalization.bloodOxygen: 'Oxygène du sang',
    StringLocalization.activeCalorieBurn: 'Brûlure active de calories',
    StringLocalization.restingCalorieBurn: 'Brûlure de calories au repos',
    StringLocalization.oxygen: 'Oxygène',
    StringLocalization.tagLevel: 'Niveau de ',
    StringLocalization.numberOfPills: 'Nombre de pilules',
    StringLocalization.glassOf: 'Verres de boisson',
    StringLocalization.numberOfSmoke: 'Nombre de cigarettes',
    StringLocalization.start: 'Commencer',
    StringLocalization.gmail: 'Gmail',
    StringLocalization.instagram: 'Instagram',
    StringLocalization.snapchat: 'Snapchat',
    StringLocalization.facebook: 'Facebook',
    StringLocalization.weibo: 'Weibo',
    StringLocalization.termsOfService: 'Conditions de Services',
    StringLocalization.syncHealthKit: "Sync les données d'Apple Santé",
    StringLocalization.syncGoogleFit: 'Sync les données de Google Fit',
    StringLocalization.clickAgain: 'Appuyez sur retour à nouveau pour quitter',
    StringLocalization.surveyList: "Liste d'enquêtes",
    StringLocalization.addSurvey: 'Ajouter une enquête',
    StringLocalization.calendarScreen: 'Calendrier',
    StringLocalization.survey: 'Enquête',
    StringLocalization.addQuestion: 'Ajouter une question',
    StringLocalization.backText: 'Retour',
    StringLocalization.selectServer: 'Sélectionner un serveur',
    StringLocalization.temperatureMonitoring: 'Surveillance de la température',
    StringLocalization.kSend: 'Envoyer',
    StringLocalization.trends: 'Les tendances',
    StringLocalization.hrBPMonitoring:
        'Surveillance de la fréquence cardiaque et de la pression artérielle',
    //StringLocalization.interpolation: 'Interpolation',
    StringLocalization.interpolation: 'Intrpl',
    StringLocalization.confirmationText: 'Voulez-vous continuer?',
    StringLocalization.setUnit: "Paramètres de l'appareil",
    StringLocalization.cameraMeasurement: 'Mesure de la caméra',
    StringLocalization.hg08Name: 'HG Genesis',
    StringLocalization.hg66Name: 'Genesis O2',
    StringLocalization.hg80Name: 'HG Phoenix',
    StringLocalization.bluetooth: 'Bluetooth',
    StringLocalization.celsiusShort: '°C',
    StringLocalization.fahrenheitShort: '°F',
    StringLocalization.unitSetSuccess: 'Appareil réglé avec succès',
    StringLocalization.intensity: 'Intensité',
    StringLocalization.searchIcon: 'Icône de recherche',
    StringLocalization.voiceConfiguration: 'Paramètres texte à la parole',
    StringLocalization.addNewTag: 'Ajouter nouvelle balise',
    StringLocalization.selectCategory: 'Sélectionnez la catégorie',
    StringLocalization.wellness: 'Bien-être',
    StringLocalization.exerciseTitle: "Nouvelle étiquette d'exercice",
    StringLocalization.wellnessTitle: 'Nouvelle étiquette de bien-être',
    StringLocalization.symptomsTitle: 'Nouvelle étiquette de symptômes',
    StringLocalization.emptyWeight: 'Entrez le poids',
    StringLocalization.takePhoto: 'Prendre une photo',
    StringLocalization.photoLibrary: 'Photothèque',
    StringLocalization.feetShort: 'ft',
    StringLocalization.noConnectionMessage:
        'Appareil non connecté. Veuillez connecter un appareil.',
    StringLocalization.addNewGraphTab: 'Voulez-vous ajouter une nouvelle catégorie?',
    StringLocalization.addNewCategory: 'Add New Category',
    StringLocalization.selectIcon: "Sélectionnez l'icône",
    StringLocalization.emptyTitle: 'Enter Title',
    StringLocalization.deleteInfo: 'Êtes-vous sûr de vouloir supprimer ce graphique?',
    StringLocalization.tts: 'Texte à la parole',
    StringLocalization.speed: 'Vitesse',
    StringLocalization.selectVoice: 'Sélectionnez la voix',
    StringLocalization.stt: 'Parole au texte',
    StringLocalization.selectYourDevice: 'Sélectionnez votre appareil',
    StringLocalization.logOutConfirmMsg: 'Êtes-vous prêt à vous déconnecter',
    StringLocalization.wifiConnectMsg: 'Connectez-vous au wifi pour transférer des données',
    StringLocalization.yourBp: 'Votre tension artérielle',
    StringLocalization.noData: 'Aucune donnée',
    StringLocalization.sysAvg: 'Moyenne systolique',
    StringLocalization.diaAvg: 'Moyenne diastolique',
    StringLocalization.cmShort: 'cm',
    StringLocalization.emptyTrashNow: 'Vidé la corbeille maintenant',
    StringLocalization.inboxIsEmpty: 'Boîte de réception est vide',
    StringLocalization.sentIsEmpty: 'Messages envoyés est vide',
    StringLocalization.draftIsEmpty: 'Brouillions est vide',
    StringLocalization.trashIsEmpty: 'Corbeille est vide',
    StringLocalization.outboxIsEmpty: "Boîte d'envoi est vide",
    StringLocalization.tagDeleteInfo: 'Êtes-vous sûr de vouloir supprimer cette étiquette?',
    StringLocalization.alreadyUsedName: 'Cette étiquette existe déjà.',
    StringLocalization.noIconFound: 'Aucune icône trouvée!',
    StringLocalization.disclaimerInfo:
        "L'application de jauge de santé et son appareil sont une aide conçue pour vous aider à améliorer votre qualité de vie. Il ne remplace pas un avis médical ou un diagnostic et cela pourrait avoir de graves conséquences sur la santé.\n\nLa jauge de santé Phoenix + FIT et l'application doivent être utilisées pour consolider et suivre les mesures de santé qui permettront un aperçu plus complet de la gestion actuelle de la santé. La jauge de santé Phoenix+FIT n'a en aucun cas un impact direct sur le diagnostic, le traitement ou la gestion de la maladie d'un individu.\n\nL'application Phoenix + FIT a été conçue pour servir de moyen de surveillance et de suivi de la santé personnelle et est destinée à être utilisée pour maintenir un mode de vie sain et comprendre sa santé et est, par conséquent, un appareil de bien-être. En aucun cas, le logiciel et la technologie d'intelligence artificielle utilisés par Health Gauge ne remplacent le jugement clinique professionnel d'un professionnel de la santé.\n\nSi vous pensez avoir un problème médical, veuillez consulter votre médecin.\n\nEN CAS DE PRISE EN CHARGE POUR UNE UTILISATION ENQUÊTE: \n\nLorsque l'application Health Gauge est prise en charge pour la recherche clinique ou une utilisation expérimentale par Santé Canada et/ou la Food and Drug Administration des États-Unis, elle ne doit être utilisée que comme indiqué et par des chercheurs qualifiés uniquement.",
    StringLocalization.disclaimer: 'Clause de non-responsabilité',
    StringLocalization.healthKitNotAvailableOnDevice:
        'Health Kit n’est pas disponible sur votre appareil',
    StringLocalization.information: 'Information',
    StringLocalization.addAnEvent: 'Ajouter un événement',
    StringLocalization.appointment: 'Nomination',
    StringLocalization.minutes: 'Minutes',
    StringLocalization.yourEvents: 'Vos événements',
    StringLocalization.eventNotAdded: 'Événement non ajouté',
    StringLocalization.eventNotdeleted: 'Événement non supprimé',
    StringLocalization.reminderNotAdded: 'Rappel non ajouté',
    StringLocalization.taskNotAdded: 'Tâche non ajoutée',
    StringLocalization.appointmentNotBooked: 'Nomination non réservé',
    StringLocalization.allDay: 'Toute la journée',
    StringLocalization.setDate: 'Fixer la date',
    StringLocalization.setTime: 'Régler le temps',
    StringLocalization.outOfTown: 'Hors de la ville',
    StringLocalization.autoDeclineNewOrExistingMeetings:
        'Refuser automatiquement les réunions et conférences nouvelles ou existantes',
    StringLocalization.task: 'Tâche',
    StringLocalization.noResultFound: 'Aucun résultat trouvé',
    StringLocalization.createFolder: 'Créer un dossier',
    StringLocalization.noRecordsFound: 'Aucun résultats trouvés',
    StringLocalization.oopsDoSomething: 'Oups ! Faites quelque chose',
    StringLocalization.allMailsAlreadyRead: 'Tous les courriels ont été lus.',
    StringLocalization.pleaseWait: 'Veuilliez attendre',
    StringLocalization.noTagsFound: 'Aucune étiquette trouvée',
    StringLocalization.disclaimer: 'Clause de non-responsabilité',

    StringLocalization.imageIsEmpty: 'L’image peut pas être vide.  Veuillez sélectioner une image.',
    StringLocalization.emailSavedInOutbox: 'Courriel enregistré dans la boîte d\'envoi avec succès',
    StringLocalization.iAccept: "J'accepte ",
    StringLocalization.agreeDisclaimerText: 'Veuillez accepter la clause de non-responsabilité',
    StringLocalization.studyCodeText:
        "Si vous connaissez le code de l'étude ou de la pratique, veuillez l'insérer, sinon laissez-le vide.",
    StringLocalization.hintForStudyCode: "Code d'étude/pratique",
    StringLocalization.userRegisteredText:
        "Merci pour votre inscription. Lorsque l'enregistrement est traité, vous recevrez un code de confirmation dans votre courrier électronique.",
    StringLocalization.iAcceptThe: "J'accepte la ",
    StringLocalization.resendCodeText:
        "Si vous n'avez pas reçu le code, cliquez ci-dessous pour obtenir le code.",
    StringLocalization.resendCode: 'Renvoyer le code',
    StringLocalization.enterDate: 'Entrer la date (jj/mm/aaaa)',
    StringLocalization.saveDataInGoogleFit: 'Sauvegarder les données dans Google Fit',
    StringLocalization.weightMeasurementDialog:
        "N'a pas obtenu de données de la balance de poids, veuillez réessayer.",
    StringLocalization.chat: 'Discute',
    StringLocalization.wifiConnect: 'UOFA',
    StringLocalization.library: 'Bibliothèque',
    StringLocalization.hrZone: 'Zone VRC',
    StringLocalization.hrZoneHistory: 'Historique des zones VRC',

    StringLocalization.tagNoteDeletedSuccessfully: 'La note de balise a été supprimée avec succès',
    StringLocalization.deletePermanently: 'Supprimer définitivement',
    StringLocalization.shareWithUser: 'Partager avec l\'utilisateur',
    StringLocalization.shareLink: 'Partager le lien',
    StringLocalization.createdFolderSuccessfully: 'Dossier créé avec succès',
    StringLocalization.deletedFileFolderSuccessfully: 'Fichier/dossier supprimé avec succès',
    StringLocalization.restoredFileFolderSuccessfully: 'Fichier/dossier restauré avec succès',
    StringLocalization.uploadedSuccessfully: 'Téléchargé avec succès',
    StringLocalization.hgSyncedSuccessfully: 'HG La montre a été synchronisée avec succès',
    StringLocalization.errorWhileUploading: 'Erreur lors du téléchargement',
    StringLocalization.errorWhileDeleting: 'Erreur lors de la suppression',
    StringLocalization.yoursFilesAreUploading: 'Vos fichiers sont en train d\'être téléchargés',
    StringLocalization.sortBy: 'Trier par',
    StringLocalization.shareWithMe: 'Partagez avec moi',
    StringLocalization.bin: 'Poubelle',
    StringLocalization.myDrive: 'MyDrive',
    StringLocalization.name: 'Nom',
    StringLocalization.lastModified: 'Dernière modification',
    StringLocalization.lastModifiedByMe: 'Dernière modification par moi',
    StringLocalization.lastOpenedByMe: 'Dernière ouverture par moi',
    StringLocalization.searchInDrive: 'Rechercher dans Drive',
    StringLocalization.createNew: 'Créer un nouveau',
    StringLocalization.create: 'Créer',
    StringLocalization.folder: 'Dossier',
    StringLocalization.upload: 'Télécharger',
    StringLocalization.deleteDialogMessage: 'Êtes-vous sûr de vouloir supprimer?',
    StringLocalization.instruction: 'Instruction',
    StringLocalization.camMeasurementInstruction1:
        'Le moniteur de fréquence cardiaque nécessite un environnement bien éclairé pour fonctionner. Si votre appareil photo est équipé d\'un flash, il s’allume automatiquement.',
    StringLocalization.camMeasurementInstruction2:
        'Si votre appareil photo n\'a pas de flash, il se peut que l\'on vous demande d\'utiliser une source d\'éclairage supplémentaire pour réduire le bruit.',
    StringLocalization.camMeasurementInstruction3:
        'Pour augmenter la précision, ne bougez pas et ne modifiez pas la pression de votre doigt pendant la mesure.',
    StringLocalization.done: 'Fini',
    StringLocalization.history: 'Histoire',

    StringLocalization.sleepReminder: 'Rappel du sommeil',
    StringLocalization.weightHistory: 'Historique du poids',
    StringLocalization.cardiacHistory: 'Antécédents cardiaques',
    StringLocalization.bodyMass: 'Masse corporelle',
    StringLocalization.requestTimeOUt: 'La demande a expiré',
    StringLocalization.temperatureHistory: 'Historique des températures',
    StringLocalization.oxygenHistory: 'Historique des l’oxygène',
    StringLocalization.spO2: 'Historique des l’oxygène',
    StringLocalization.forgotPassword: 'Mot de passe',
    StringLocalization.forgotId: 'Oublier le ID',
    StringLocalization.oxygenMonitoring: 'Surveillance de l\'oxygène',
    StringLocalization.updateFirmware: 'Mise à jour du firmware',
    StringLocalization.noEventsFound: 'Aucun événement trouvé', // todo

    StringLocalization.invitationAcceptedSuccessfully: 'Invitation été accepté.',
    StringLocalization.firstNameValidation:
        'Le prénom doit comporter au minimum 2 et au maximum 50 caractères.',
    StringLocalization.lastNameValidation:
        'Le nom de famille doit comporter au minimum 2 et au maximum 50 caractères.',

    StringLocalization.january: 'Janvier',
    StringLocalization.february: 'Février',
    StringLocalization.march: 'Mars',
    StringLocalization.april: 'Avril',
    StringLocalization.may: 'Mai',
    StringLocalization.june: 'Juin',
    StringLocalization.july: 'Juillet',
    StringLocalization.august: 'Août',
    StringLocalization.september: 'Septembre',
    StringLocalization.october: 'Octobre',
    StringLocalization.november: 'Novembre',
    StringLocalization.december: 'Décembre',
    StringLocalization.titleDbp: 'Tension diastolique',
    StringLocalization.activityTrackScreen: "Traqueur d'activité",
    StringLocalization.collectData: 'Collecte des données',
    StringLocalization.cardiac: 'Cardiaque',
    StringLocalization.viewData: 'Voir les données',
    StringLocalization.areYouSureWantToStopMeasurement:
        'Vous êtes sûr de vouloir arrêter la mesure?',
    StringLocalization.dataCollected: 'Données collectées',
    StringLocalization.notificationCenter: 'Centre de notification',
    StringLocalization.hgServer: 'HG Server', //todo
    StringLocalization.areYouReadyToEmptyYourTrash: 'Êtes-vous prêt à vider la poubelle?',
    StringLocalization.messageDeletedFromTrashSuccessfully:
        'Message supprimé de la poubelle avec succès', // todo
    StringLocalization.changePassword: 'Changer le mot de passe',
    StringLocalization.voiceSetting: 'Paramètres vocaux',
    StringLocalization.oldPassword: 'Ancien mot de passe',
    StringLocalization.confirmNewPassword: 'Confirmez le nouveau mot de passe.',
    StringLocalization.oldPasswordDoesNotMatch: 'L\'ancien mot de passe ne correspond pas.',
    StringLocalization.shutDown: 'Fermeture',
    StringLocalization.heartRateHistory: 'Historique de la fréquence cardiaque',
    StringLocalization.measurementType: 'Type de mesure',
    StringLocalization.notice: 'Avis',
    StringLocalization.forgotUserId: 'Identifiant d\'utilisateur oublié',
    StringLocalization.downloadFirmware: 'Télécharger le firmware',
    StringLocalization.auto_sync_data: 'Synchronisation automatique',
    StringLocalization.onlyMe: 'Seulement moi',
    StringLocalization.everyone: 'Tout le monde',
    StringLocalization.saySomethingAboutThisPhoto: 'Dites quelque chose à propos de ces photos',
    StringLocalization.workoutPhotos: 'Photos d\'entraînement',
    StringLocalization.basedOnYourMaxHeartRate: 'En fonction de votre fréquence cardiaque maximale',
    StringLocalization.heartRateZones: 'Zones de fréquence cardiaque',
    StringLocalization.earlier: 'Plus tôt',
    StringLocalization.news: 'Nouveau',
    StringLocalization.notifications: 'Notifications',
    StringLocalization.workoutFeeds: 'Flux d\'entraînement',
    StringLocalization.comment: 'Commentaire',
    StringLocalization.likes: 'J’aime',
    StringLocalization.viewAnalysis: 'Voir l\'analyse',
    StringLocalization.workoutAnalysis: 'Analyse des entraînements',
    StringLocalization.elevation: 'Élévation',
    StringLocalization.speed: 'Vitesse',
    StringLocalization.activityHistory: 'Historique des activités',
    StringLocalization.saveWorkout: 'Sauvegarder l\'entraînement',
    StringLocalization.discard: 'Jeter',
    StringLocalization.typeNotesHere: 'Tapez vos notes ici',
    StringLocalization.howWasYourRun: 'Comment s\'est passée ta course?',
    StringLocalization.friends: 'Amis',
    StringLocalization.resume: 'Reprendre',
    StringLocalization.finish: 'Finir',
    StringLocalization.pause: 'Pause',
    StringLocalization.workoutRecord: 'Dossier d\'entraînement',
    StringLocalization.duration: 'Durée',
    StringLocalization.microphone: 'Microphone',
    StringLocalization.resend: 'Renvoyer',
    StringLocalization.pleaseEnterTheSixDigitCodeSentToYourEmail:
        'Veuillez saisir le code à six chiffres envoyé à votre courriel.',
    StringLocalization.pleaseEnterTheSixDigitCodeSentToYourPhone:
        'Veuillez saisir le code à six chiffres envoyé à votre numéro de téléphone.',

    StringLocalization.onConnect: 'Connecté avec succès à la prise...',
    StringLocalization.onConnectError:
        'Erreur lors de la connexion à la prise, veuillez réessayer!',
    StringLocalization.onConnectTimeout: 'Délai de connection dépassé!',
    StringLocalization.noClientFoundInNetwork: 'Aucun client trouvé dans le réseau !',

    StringLocalization.verify: 'Vérifier',
    StringLocalization.pleaseEnterYourNewPassword: 'Veuillez entrer votre nouveau mot de passe',
    StringLocalization.addPassword: 'Ajouter un mot de passe',
    StringLocalization.verificationCode: 'Code de vérification',
    StringLocalization.errorWhileRequestTryAgainLater:
        'Erreur lors de la demande, réessayez plus tard.',
    StringLocalization.noRecordWithUserId:
        'Nous n\'avons pas d\'enregistrement avec cet ID utilisateur dans notre système.',
    StringLocalization.incorrectUserId: 'ID utilisateur incorrect',
    StringLocalization.error: 'Erreur',
    StringLocalization.noPhoneNumberAssociated:
        'Aucun numéro de téléphone n\'est associé à votre compte.',
    StringLocalization.noEmailAssociated: 'Aucun courriel n\'est associé à votre compte.',
    StringLocalization.whereAuthenticationCode:
        'Veuillez sélectionner l\'endroit où vous souhaitez que votre code d\'authentification soit envoyé.',
    StringLocalization.passwordChangedSuccessfully: 'Le mot de passe a été modifié avec succès',
    StringLocalization.min8toMax20:
        'Doit comporter entre 8 caractères au minimum et 20 caractères au maximum',
    StringLocalization.oneUppercase: 'Doit contenir au moins une lettre majuscule',
    StringLocalization.oneLowercase: 'Doit contenir au moins une lettre minuscule',
    StringLocalization.oneSpecialCharacter: 'Doit contenir au moins un caractère spécial',
    StringLocalization.oneNumber: 'Doit contenir au moins un numéro',
    StringLocalization.enterHeight: 'Entrez la hauteur',
    StringLocalization.distanceKm: 'Distance (Km)',
    StringLocalization.pace: 'Vitesse (km/hr)',
    StringLocalization.pace1: 'Vitesse (mile/hr)',
    StringLocalization.avgPace: 'Vitesse moyenne (km/h)',
    StringLocalization.avgPace1: 'Vitesse moyenne (Mile/hr)',
    StringLocalization.startWorkout: 'Commencer l\'entraînement',
    StringLocalization.agree: 'D\'accord',
    StringLocalization.disagree: 'Pas d\'accord',
    StringLocalization.oldNewPassword: 'Old and New password must be different.',
    StringLocalization.hrvRmssd: 'HRV (RMSSD)',
    StringLocalization.userLoggedInSuccessfully: 'S\'est connecté avec succèsn', // todo
    StringLocalization.rememberMe: 'se souvenir de moi',
    StringLocalization.passwordMismatch: 'le mot de passe doit correspondre',
    StringLocalization.passwordInvalid: 'Mot de passe incorrect',
    StringLocalization.fetchAndNext: 'Récupérer et suivant',
    StringLocalization.readDisclaimer:
        'Veuillez lire la clause de non-responsabilité avant de vous inscrire',
    StringLocalization.readTermsAndConditions:
        'Veuillez lire les termes et conditions avant de vous inscrire',
    StringLocalization.userRegisteredSuccessfully: 'Inscription réussie',
    StringLocalization.weightConnectionType: 'Weight Connection Type', // todo
    StringLocalization.enterValidWeight: 'Entrez un poids valide',
    StringLocalization.maxWeightLimit: 'Entrez un poids inférieur à',
    StringLocalization.enterValidHeight: 'Entrez une hauteur valide',
    StringLocalization.maxHeightLimitCm: 'Entrez une taille inférieure à 241 cm',
    StringLocalization.enterFeet: 'Entrez pieds',
    StringLocalization.enterInch: 'Entrez pouces',
    StringLocalization.maxHeightLimitFeet: 'Entrez une taille inférieure à 7 pieds et 11 pouces',
    StringLocalization.inchLimit: 'Pouces ne peut être supérieure à 12',
    StringLocalization.bloodPressureHistory: 'Historique des tension artérielle',
    StringLocalization.graphNormalization: 'Normalization',
    StringLocalization.tagNoteDeleteInfo:
        'Êtes-vous sûr de vouloir supprimer cette note d\'étiquette?',
    StringLocalization.measurementDeleteInfo: 'Êtes-vous sûr de vouloir supprimer cette mesure?',
    StringLocalization.discardWorkout: 'Supprimer l\'entraînement',
    StringLocalization.areYouSureYouWantToDiscardTheWorkout:
        'Êtes-vous sûr de vouloir supprimer cet entraînement?',
    StringLocalization.pleaseConnectTheInternet: 'Please connect the internet',
    StringLocalization.close: 'Fermer',
    StringLocalization.maxSpeed: 'Vitesse maximale',
    StringLocalization.touchElectrod: 'Touchez l\'électrode',
    StringLocalization.tempInfo:
        'La température normale du corps humain (normothermie, euthermie) est la gamme de température typique de l\'homme. La température normale du corps humain est généralement comprise entre 36,5 et 37,5 °C (97,7 à 99,5 °F).\n\nLa température du corps humain varie. Elle dépend du sexe, de l\'âge, de l\'heure de la journée, du niveau de fatigue, de l\'état de santé (comme la maladie et les menstruations), de la partie du corps où la mesure est effectuée, de l\'état de conscience (éveillé, endormi, sous sédatif) et des émotions. La température du corps est maintenue dans la gamme normale par la thermorégulation, dans laquelle l\'ajustement de la température est déclenché par le système nerveux central.\n\nChaud\n\n44 °C (111,2 °F) ou plus – La mort est presque certaine; cependant, on sait que des personnes ont survécu jusqu\'à 46,5 °C (115,7 °F).\n\n43 °C (109,4 °F) - Normalement la mort, ou il peut y avoir de graves lésions cérébrales, des convulsions continues et un choc. Un collapsus cardio-respiratoire est probable.\n\n42 °C (107,6 °F) - Le sujet peut devenir pâle ou rester rouge et rougir. Il peut devenir comateux, avoir un délire grave, vomir et avoir des convulsions. La pression artérielle peut être élevée ou basse et le rythme cardiaque sera très rapide.\n\n41 °C (105,8 °F) - (Urgence médicale) - Des évanouissements, des vomissements, de graves maux de tête, des étourdissements, de la confusion, des hallucinations, du délire et de la somnolence peuvent survenir. Il peut également y avoir des palpitations et un essoufflement.\n\n40 °C (104 °F) - Des évanouissements, une déshydratation, une faiblesse, des vomissements, des maux de tête, un essoufflement et des étourdissements peuvent survenir ainsi qu\'une transpiration abondante. Commence à mettre la vie en danger.\n\n39 °C (102,2 °F) - Transpiration intense, rougeur et rougissement. Fréquence cardiaque rapide et essoufflement. Cela peut s\'accompagner d\'un épuisement. Les enfants et les personnes épileptiques sont très susceptibles d\'avoir des convulsions à ce stade.\n\n38 °C (100,4 °F) - (Classée comme hyperthermie si elle n\'est pas causée par une fièvre) - Sensation de chaleur, transpiration, sensation de soif, sensation de malaise, légère faim. Si cela est dû à la fièvre, il peut également y avoir des frissons.\n\nNormal\n\n36,5-37,5 °C (97,7-99,5 °F) est une gamme typiquement rapportée pour la température corporelle normale.\n\nFroid\n\n36 °C (96,8 °F) - Sensation de froid, frissons légers à modérés. La température corporelle peut descendre aussi bas pendant le sommeil. Il peut s\'agir d\'une température corporelle normale.\n\n35 °C (95 °F) - (L\'hypothermie est inférieure à 35 °C (95 °F)) - Frissons intenses, engourdissement et teinte bleutée/grise de la peau. Il existe une possibilité d\'irritabilité cardiaque.\n\n34 °C (93,2 °F) - Frissons intenses, perte des mouvements des doigts, peau bleue et confusion. Certains changements de comportement peuvent survenir.\n\n33 °C (91,4 °F) - Confusion modérée à grave, somnolence, réflexes déprimés, perte progressive des frissons, ralentissement du rythme cardiaque, respiration superficielle. Les frissons peuvent s\'arrêter. Le sujet peut ne pas réagir à certains stimuli.\n\n32 °C (89,6 °F) - (Urgence médicale) - Hallucinations, délire, confusion totale, somnolence extrême qui devient progressivement comateuse. Les frissons sont absents (le sujet peut même penser qu\'il a chaud). Les réflexes peuvent être absents ou très faibles.\n\n31 °C (87,8 °F) - Comateux, très rarement conscient. Réflexes inexistants ou faibles. Respiration très superficielle et rythme cardiaque lent. Possibilité de graves problèmes de rythme cardiaque.\n\n28 °C (82,4 °F) - De graves troubles du rythme cardiaque sont probables et la respiration peut s\'arrêter à tout moment. Le patient peut sembler mort.\n\n24-26 °C (75,2-78,8 °F) ou moins - La mort survient généralement en raison d\'un rythme cardiaque irrégulier ou d\'un arrêt respiratoire ; cependant, on sait que certains patients ont survécu avec des températures corporelles aussi basses que 14,2 °C (57,6 °F).',
    StringLocalization.bpInfo:
        'Les données présentées sont à titre indicatif et ne sont pas considérées comme des données médicales.\n\nCet dispositif n\'est pas destiné à un usage médical. Veuillez consulter votre médecin pour tout ce qui concerne votre santé.\n\nLes cinq gammes de pression artérielle reconnues par l\'American Heart Association sont les suivantes:\n\nNormal - Les chiffres de pression artérielle inférieurs à 120/80 mm Hg sont considérés comme se situant dans la gamme normale. Si vos résultats se situent dans cette catégorie, conservez des habitudes saines pour le cœur, comme suivre un régime alimentaire équilibré et faire régulièrement de l\'exercice.\n\nÉlevée - La pression artérielle est considéré comme élevée lorsque les mesures se situent constamment entre 120 et 129 mm Hg pour la tension systolique et moins de 80 mm Hg pour la tension diastolique. Les personnes ayant une pression artérielle élevée sont susceptibles de développer une hypertension artérielle, à moins que des mesures ne soient prises pour contrôler cette condition.\n\nStade 1 de l\'hypertension - On parle de stade 1 de l\'hypertension lorsque la pression artérielle se situe constamment entre 130 et 139 mm Hg pour la systolique et entre 80 et 89 mm Hg pour la diastolique. À ce stade de l\'hypertension, les médecins prescriront probablement des modifications du mode de vie et pourront envisager d\'ajouter des médicaments contre l\'hypertension en fonction de votre risque de maladie cardiovasculaire athérosclérotique (MCAV), telle qu\'une crise cardiaque ou un accident cérébral...\n\nHypertension de stade 2 - On parle d\'hypertension de stade 2 lorsque la pression artérielle est constamment égale ou supérieure à 140/90 mm Hg. À ce stade de la pression artérielle, les médecins sont susceptibles de prescrire une combinaison de médicaments contre la pression artérielle et de modifications du mode de vie.\n\nCrise hypertensive - Ce stade de l\'hypertension artérielle nécessite une attention médicale. Si votre tension artérielle est supérieure à 180/120 mm Hg et que vous présentez des signes de lésions des organes possibles, tels que des douleurs thoraciques, un essoufflement, des douleurs de dos, des engourdissements/faiblesses, une modification de la vision ou des difficultés à parler, n\'attendez pas de voir si votre tension baisse d\'elle-même. Appelez immédiatement une aide médicale d\'urgence.\n\nNote: Un diagnostic d\'hypertension artérielle doit être confirmé par un professionnel de la santé. Un médecin doit également évaluer toute mesure de pression artérielle anormalement basse.\n\nSource : American Heart Association',
    StringLocalization.hrvInfo:
        'La variabilité de la fréquence cardiaque, VFC, est la variation de l\'intervalle entre les battements du cœur. Le VFC augmente toujours quand quelqu\'un se sent mieux. L\'objectif est généralement d\'obtenir la valeur de VRC la plus élevée possible au fil du temps, mais il faut s\'attendre à quelques baisses lors d\'un entraînement intensif.\n\nCette variation est contrôlée par une partie primitive du système nerveux appelée le système nerveux autonome (SNA), qui contrôle également notre fréquence cardiaque, notre pression artérielle, notre respiration et notre digestion.\n\nSi nous sommes confrontés à des facteurs persistants tels que le stress, le manque de sommeil, une mauvaise alimentation, des relations dysfonctionnelles, l\'isolement ou la solitude, et le manque d\'exercice, notre réaction de lutte ou de fuite peut passer à la surmultipliée et provoquer une baisse du VFC. Si l\'on est dans un état plus détendu, la variation entre les battements est élevée.\n\nLe VFC est un moyen intéressant et non invasif d\'identifier ces déséquilibres du système nerveux automatique. Un faible VFC est même associé à un risque plus élevé de décès et de maladies cardiovasculaires.\n\nSource : École de médecine de Harvard',
    StringLocalization.spO2Info:
        'Qu\'est-ce que la saturation en oxygène du sang (SpO2)? \n\ntaux de saturation d\'oxygène dans le sangLa saturation en oxygène du sang (SpO2) est le pourcentage d\'hémoglobine dans le sang qui contient de l\'oxygène - en d\'autres termes, la quantité d\'oxygène dans le sang. Il s\'agit d\'un indicateur naturel utile de l\'état du système respiratoire d\'une personne. Si votre SpO2 est inférieure à 90%, vous risquez de développer une hypoxémie. De manière générale, plus votre SpO2 est inférieure à 90%, plus vous risquez de développer une hypoxémie. D\'une manière générale, plus votre SpO2 est basse, plus le risque est élevé. Utilisez les données ci-dessous à titre de référence:\n\nNote: La gamme de mesure de cet appareil est de 50%-100%.\n\nPoints importants à noter lors de la mesure de la SpO2:\n\nActivez la fonction SpO2 sur le dispositif portable. Suivez les instructions de votre dispositif pour obtenir les résultats les plus précis.\n\nCertains facteurs externes peuvent interférer avec la mesure, la rendant imprécise ou même impossible à mesurer. Il s\'agit notamment d\'un faible débit sanguin, de poils sur le bras, de tatouages, d\'une peau lâche, du fait de bouger le bras pendant la mesure, de ne pas porter correctement votre appareil, de la température ambiante, etc.\n\nLes résultats des mesures sont donnés à titre de référence uniquement et ne sont pas destinés à servir de base à un diagnostic médical.',

    StringLocalization.glucoseCalibrationTag: 'Étalonnage du glucose P5.0',
    StringLocalization.fingerStick1Glucose: 'Mesure du glucose au bout du doigt 1',
    StringLocalization.fingerStick2Glucose: 'Mesure du glucose au bout du doigt 2',
    StringLocalization.glucoseCalibrationHelp:
        'Pour calibrer l\'appareil P5.0 Glucose, des mesures de glucose à deux doigts sont nécessaires. Veuillez prendre deux mesures à l\'aide de votre lecteur de glycémie Finger Stick et sur la page d\'étalonnage. Veuillez vous assurer que tous les champs sont remplis avec des informations précises et que les deux mesures sont dans la même unité. Le fait de ne pas fournir d\'informations précises peut entraîner une estimation inexacte de la part du Patch.',
    StringLocalization.ble_devices: 'Appareils mobiles',
    StringLocalization.transmit_command: 'Transmettre la commande',
    StringLocalization.connect: 'Connecter',
    StringLocalization.device_connect_successfully: 'L\'appareil s\'est connecté avec succès',
    StringLocalization.enter: 'Entrer',

    StringLocalization.imageLogin: 'asset/Help/logInF.jpg',
    StringLocalization.imageSignUp: 'asset/Help/signupF.jpg',
    StringLocalization.imageResetPassword: 'asset/Help/resetPasswordF.jpg',
    StringLocalization.imageDashboard: 'asset/Help/homeF.jpg',
    StringLocalization.imageProfile: 'asset/Help/profileF.jpg',
    StringLocalization.imageConnection: 'asset/Help/connectionF.jpg',
    StringLocalization.imageSetting: 'asset/Help/settingF.jpg',
    StringLocalization.imageActivityDay: 'asset/Help/activityDayF.jpg',
    StringLocalization.imageActivityWeek: 'asset/Help/activityWeekF.jpg',
    StringLocalization.imageSleep: 'asset/Help/sleepF.jpg',
    StringLocalization.imageTag: 'asset/Help/tagF.jpg',
    StringLocalization.imageTagEditor: 'asset/Help/tagEditorF.jpg',
    StringLocalization.imageTagUpdate: 'asset/Help/tagUpdateF.jpg',
    StringLocalization.imageGraph: 'asset/Help/graphF.jpg',
    StringLocalization.imageMeasurementHistory: 'asset/Help/measurementHistoryF.jpg',
    StringLocalization.imageTagHistory: 'asset/Help/tagHistoryF.jpg',
    StringLocalization.imageDeviceManagement: 'asset/Help/deviceManagementF.jpg',
    StringLocalization.imageFindBracelet: 'asset/Help/findBraceletF.jpg',
    StringLocalization.imageTraining: 'asset/Help/trainingF.jpg',
    StringLocalization.imageWearingMethod: 'asset/Help/wearingMethodF.jpg',
    StringLocalization.imageWearingMethod2: 'asset/Help/wearing_methodF.png',
    StringLocalization.imageHourlyHR: 'asset/Help/hourlyHRF.jpg',
    StringLocalization.imageBrightenScreen: 'asset/Help/brightenScreenF.jpg',
    StringLocalization.imageBrightenScreen2: 'asset/Help/brighten_screenF.png',
    StringLocalization.imageDoNotDisturb: 'asset/Help/doNotDisturbF.jpg',
    StringLocalization.imageDoNotDisturb2: 'asset/Help/do_not_disturbF.png',
    StringLocalization.imageTimeFormat: 'asset/Help/timeFormatF.jpg',
    StringLocalization.imageMeasurement: 'asset/Help/measurementF.jpg',
  };
}
