import 'string_localization.dart';

/// Added by: Akhil
/// Added on: May/28/2020
/// This class contains all the Strings which are used in app in Hindi Language

class HindiLocalization{
  static Map<String,String> getLocalization = {
    StringLocalization.kValues:'मान',
    StringLocalization.kMeasurement:'माप',
    StringLocalization.dashBoardName: 'स्वास्थ्य गेज',
    StringLocalization.cnctnScreen: 'संबंध',
    StringLocalization.settingScreen: 'समायोजन',
    StringLocalization.targetScreen: 'कदम लक्ष्य',
    StringLocalization.tagHistory: 'टैग इतिहास',
    StringLocalization.sleeptargetScreen: 'नींद लक्ष्य',
    StringLocalization.btnTitle: 'बटन शीर्षक',
    StringLocalization.btnTag: 'टैग जोड़ो',
    StringLocalization.btnTagU: 'अपडेट टैग',
    StringLocalization.displayOne: 'प्रदर्शन एक',
    StringLocalization.tagScreen: 'टैग',
    StringLocalization.tagScreenSlctn: 'टैग चयन',
    StringLocalization.headline: 'शीर्षक',
    StringLocalization.subHeadline: 'दूसरा नाम',
    StringLocalization.title: 'शीर्षक',
    StringLocalization.subTitle: 'उप शीर्षक',
    StringLocalization.body2: 'Body2',
    StringLocalization.body1: 'body1',
    StringLocalization.small: 'छोटा',
    StringLocalization.caption: 'शीर्षक',
    StringLocalization.appbarMgmt: 'डिवाइस प्रबंधन',
    StringLocalization.monitor: 'कनेक्ट डिवाइस',
    StringLocalization.timeFormat: 'समय प्रारूप',
    StringLocalization.timeF: '24 घंटों',
    StringLocalization.timeFo: '12h',
    StringLocalization.reset: 'रीसेट',
    StringLocalization.hrMonitor: 'हर घंटे का मानव संसाधन मॉनिटर',
    StringLocalization.bScreen: 'कलाई को चमकदार स्क्रीन लिफ्ट',
    StringLocalization.dNd: 'परेशान न करें',
    StringLocalization.firmUpdate: 'फर्मवेयर अपडेट',
    StringLocalization.noInternet: 'ऊप्स!',
    StringLocalization.enableInternet: 'लगता है जैसे आप इंटरनेट से कनेक्ट नहीं कर रहे हैं। अपने डेटा कनेक्शन सक्षम',
    StringLocalization.retry: 'पुन: प्रयास करें',
    StringLocalization.cncl: 'रद्द करना',
    StringLocalization.mileage: 'लाभ',
    StringLocalization.kCal: 'किलो कैलोरी',
    StringLocalization.comp: 'समापन',
    StringLocalization.hintForUserId: 'यूज़र आईडी',
    StringLocalization.hintForPassword: 'कुंजिका',
    StringLocalization.hintForNewPassword: 'नया पासवर्ड',
    StringLocalization.loginBtn: 'लॉग इन करें',
    StringLocalization.type: 'प्रकार',
    StringLocalization.stps: 'कदम',
    StringLocalization.value: 'मूल्य',
    StringLocalization.time: 'समय',
    StringLocalization.date: 'तारीख',
    StringLocalization.notes: 'टिप्पणियाँ',
    StringLocalization.day: 'दिन',
    StringLocalization.week: 'सप्ताह',
    StringLocalization.month: 'महीना',
    StringLocalization.timeH: 'समय',
    StringLocalization.typeH: 'प्रकार',
    StringLocalization.valueH: 'मूल्य',
    StringLocalization.noteH: 'ध्यान दें',
    StringLocalization.weekH: 'इस सप्ताह',
    StringLocalization.lastH: 'पिछले सप्ताह',
    StringLocalization.skipBtn: 'छोड़ें',
    StringLocalization.btnForgotPassword: 'पासवर्ड भूल गए?',
    StringLocalization.next: 'आगे',
    StringLocalization.dontHaveAnAccount: 'एक खाता नहीं है?',
    StringLocalization.btnSignUp: 'साइन अप करें',
    StringLocalization.btnConnect: 'जुडिये',
    StringLocalization.btnDisConnect: 'डिस्कनेक्ट',
    StringLocalization.emptyUserId: 'प्रयोक्ता-आईडी दर्ज करें',
    StringLocalization.emptyPassword: 'पास वर्ड दर्ज करें',
    StringLocalization.emptyNewPassword: 'नया पासवर्ड दर्ज करें',
    StringLocalization.btnLogout: 'लॉग आउट',
    StringLocalization.hintForEmail: 'ईमेल',
    StringLocalization.emptyEmail: 'ईमेल दर्ज करें',
    StringLocalization.enterValidEmail: 'मान्य ईमेल दर्ज करें',
    StringLocalization.hintForFirstName: 'पहला नाम',
    StringLocalization.emptyFirstName: 'पहला नाम दर्ज करें',
    StringLocalization.hintForLastName: 'उपनाम',
    StringLocalization.emptyLastName: 'अंतिम नाम दर्ज करो',
    StringLocalization.hintForBirthDate: 'जन्म दिन',
    StringLocalization.emptyBirthDate: 'जन्म तिथि दर्ज',
    StringLocalization.hintForPhone: 'फ़ोन नंबर',
    StringLocalization.emptyPhone: 'फोन नंबर दर्ज',
    StringLocalization.enterValidPhone: 'मान्य फ़ोन नंबर डालें',
    StringLocalization.confirmPasswordDoesntMatch: 'पुष्टि पासवर्ड मेल नहीं खाता',
    StringLocalization.hintForConfirmPassword: 'पासवर्ड की पुष्टि कीजिये',
    StringLocalization.emptyConfirmPassword: 'पुष्टि पासवर्ड दर्ज करें',
    StringLocalization.passwordInvalid: 'अवैध पासवर्ड',
    StringLocalization.termsAndConditions: 'नियम और शर्तें',
    StringLocalization.readMore: 'अधिक पढ़ें।',
    StringLocalization.agreeTermsAndCondition: 'कृपया नियम और शर्तें स्वीकार करें।',
    StringLocalization.save: 'सहेजें',
    StringLocalization.profile: 'प्रोफ़ाइल',
    StringLocalization.pleaseLoginFirstToUseThisFeature: 'लॉग इन पहले इस सुविधा का उपयोग करने के लिए कृपया?',
    StringLocalization.cancel: 'रद्द करना',
    StringLocalization.ok: 'ठीक',
    StringLocalization.deviceBattery: 'डिवाइस बैटरी',
    StringLocalization.bp: 'बीपी',
    StringLocalization.offLineEcgSbp: '0/0',
    StringLocalization.heartRate: 'हृदय गति',
    StringLocalization.hrv: 'मानव संसाधन V',
    StringLocalization.health: 'स्वास्थ्य',
    StringLocalization.symptoms: 'लक्षण',
    StringLocalization.complete: 'पूर्ण',
    StringLocalization.steps: 'कदम',
    StringLocalization.calories: 'कैलोरी',
    StringLocalization.kml: 'किलो कैलोरी',
    StringLocalization.zeroKml: 'kml',
    StringLocalization.distance: 'दूरी',
    StringLocalization.km: 'किमी',
    StringLocalization.zeroKm: '0 किमी',
    StringLocalization.activity: 'गतिविधि',
    StringLocalization.sleepS: 'नींद',
    StringLocalization.sleepHour: 'नींद घंटे',
    StringLocalization.hour: 'घंटा',
    StringLocalization.sleep: 'नींद',
    StringLocalization.disconnect: 'डिस्कनेक्ट!',
    StringLocalization.areYouSureWantToDisconnect: 'क्या आप वाकई डिस्कनेक्ट करना चाहते हैं',
    StringLocalization.connectedDevice: 'कनेक्टेड डिवाइस',
    StringLocalization.connected: 'जुड़े हुए',
    StringLocalization.disconnected: 'डिस्कनेक्ट किया गया',
    StringLocalization.andConnect: 'और कनेक्ट',
    StringLocalization.gender: 'लिंग',
    StringLocalization.male: 'पुरुष',
    StringLocalization.female: 'महिला',
    StringLocalization.unit: 'इकाई',
    StringLocalization.metric: 'मीट्रिक',
    StringLocalization.imperial: 'शाही',
    StringLocalization.dateOfBirth: 'जन्म की तारीख',
    StringLocalization.selectBirthDate: 'चुनें जन्म तिथि',
    StringLocalization.height: 'ऊंचाई',
    StringLocalization.confirm: 'पुष्टि करें',
    StringLocalization.feet: 'पैर का पंजा',
    StringLocalization.inch: 'इंच',
    StringLocalization.skinPhotoType: 'त्वचा छापने की विधि',
    StringLocalization.width: 'चौड़ाई',
    StringLocalization.lb: 'LB',
    StringLocalization.measurement: 'माप',
    StringLocalization.startMeasurement: 'प्रारंभ माप',
    StringLocalization.training: 'प्रशिक्षण',
    StringLocalization.hrBPM: 'मानव संसाधन (बीपीएम)',
    StringLocalization.bpMmHg: 'बीपी',
    StringLocalization.countDown: 'उलटी गिनती:',
    StringLocalization.ecg: 'ईसीजी',
    StringLocalization.ppg: 'पिपिजी',
    StringLocalization.calibration: 'कैलिब्रेशन',
    StringLocalization.hr: 'हृदय गति',
    StringLocalization.sbd: 'सिस्टोलिक रक्तचाप',
    StringLocalization.dbp: 'डायस्टोलिक रक्तचाप',
    StringLocalization.shortDescription: 'अपने दोलायमान डिवाइस से रीडिंग दर्ज करें।',
    StringLocalization.add: 'जोड़ें',
    StringLocalization.addToGraph: 'जोड़ने के लिए ग्राफ',
    StringLocalization.measurementHistory: 'मापन इतिहास',
    StringLocalization.today: 'आज',
    StringLocalization.yesterday: 'बिता कल',
    StringLocalization.tomorrow: 'आने वाला कल',
    StringLocalization.stopMeasurement: 'बंद करो मापन',
    StringLocalization.edit: 'संपादित करें',
    StringLocalization.camera: 'तस्वीर ले लो',
    StringLocalization.gallery: 'फोन में से चुनें',
    StringLocalization.remove: 'हटाना',
    StringLocalization.min: 'मिन',
    StringLocalization.max: 'मैक्स',
    StringLocalization.enterMin: 'मिन दर्ज',
    StringLocalization.minMustBeSmallerThenMax: 'अमान्य मूल्य',
    StringLocalization.enterMax: 'मैक्स दर्ज',
    StringLocalization.minMustBeSmallerThenMin: 'अमान्य मूल्य',
    StringLocalization.label: 'टैग लेबल',
    StringLocalization.enterLabel: 'टैब लेबल दर्ज करें',
    StringLocalization.defaultValue: 'दर्ज मूल्य',
    StringLocalization.enterBetween: 'के बीच दर्ज करें',
    StringLocalization.digit: 'अंक',
    StringLocalization.enterDigit: 'डिजिट दर्ज',
    StringLocalization.centimetre: 'सेंटीमीटर',
    StringLocalization.kg: 'किलोग्राम',
    StringLocalization.weight: 'वजन',
    StringLocalization.updatedSuccessfully: 'अद्यतन सफलतापूर्ण हो गया',
    StringLocalization.failToUpdate: 'असफल अद्यतन करने के लिए',
    StringLocalization.sleepHistoryTitle: 'नींद',
    StringLocalization.chooseYourStepTarget: 'अपने कदम लक्ष्य चुनें',
    StringLocalization.stepSuggestion: 'सुझाव 8000 ~ 10000 प्रत्येक दिन कदम',
    StringLocalization.chooseSleepTarget: 'आपकी नींद लक्ष्य चुनें',
    StringLocalization.sleepSuggestion: '9 घंटे एक दिन - वयस्कों 7 सो करने का सुझाव',
    StringLocalization.noDataFound: 'कोई डेटा नहीं मिला।',
    StringLocalization.stayUp: 'जागते रहना',
    StringLocalization.light: 'रोशनी',
    StringLocalization.deep: 'गहरा',
    StringLocalization.commingSoon: 'जल्द आ रहा है',
    StringLocalization.target: 'लक्ष्य',
    StringLocalization.minute: 'मिनट',
    StringLocalization.privacyPolicy: 'गोपनीयता नीति',
    StringLocalization.tagLabelEditor: 'टैग लेबल संपादक',
    StringLocalization.addTagTitle: 'नया टैग जोड़ें',
    StringLocalization.update: 'अपडेट करें',
    StringLocalization.selectTag: 'चयनित टैग',
    StringLocalization.range: 'रेंज',
    StringLocalization.minimum: 'न्यूनतम',
    StringLocalization.maximum: 'ज्यादा से ज्यादा',
    StringLocalization.defaultValueTag: 'डिफ़ॉल्ट मान:',
    StringLocalization.precision: 'शुद्धता',
    StringLocalization.tag: 'टैग',
    StringLocalization.tagValue: 'मान:',
    StringLocalization.change: 'परिवर्तन',
    StringLocalization.addNote: 'टैग जोड़ो',
    StringLocalization.updateNote: 'अद्यतन टैग',
    StringLocalization.enterUnit: 'यूनिट दर्ज करें',
    StringLocalization.stress: 'तनाव',
    StringLocalization.number: 'संख्या',
    StringLocalization.fatigue: 'थकान',
    StringLocalization.bloodGlucose: 'रक्त ग्लूकोज',
    StringLocalization.exercise: 'व्यायाम',
    StringLocalization.bodyTemperature: 'शरीर का तापमान',
    StringLocalization.celsius: 'सेल्सीयस',
    StringLocalization.breathing: 'साँस लेने का',
    StringLocalization.deviceManagement: 'डिवाइस प्रबंधन',
    StringLocalization.hourlyHrMonitor: 'हर घंटे का मानव संसाधन मॉनिटर',
    StringLocalization.liftTheWristBrighten: 'लिफ्ट कलाई करने के लिए रौशन स्क्रीन',
    StringLocalization.doNotDisturb: 'परेशान न करें',
    StringLocalization.twelve: '12h',
    StringLocalization.twentyFour: '24 घंटों',
    StringLocalization.wearType: 'पहने हुए विधि',
    StringLocalization.leftHand: 'बाएं',
    StringLocalization.rightHand: 'दाहिने',
    StringLocalization.graph: 'ग्राफ़',
    StringLocalization.selectItem: 'वस्तु चुनें',
    StringLocalization.somethingWentWrong: 'कुछ गलत हो गया',
    StringLocalization.oops: 'ओह!',
    StringLocalization.unknown: 'अनजान',
    StringLocalization.healthGauge: 'healthGauge',
    StringLocalization.helpForMeasurement: 'माप',
    StringLocalization.help: 'मदद',
    StringLocalization.findBracelet: 'कंगन का पता लगाएं',
    StringLocalization.version: 'संस्करण',
    StringLocalization.localization: 'स्थानीयकरण',
    StringLocalization.chooseSelectedLanguage: 'भाषा बदलने के लिए स्विच ऑन करें',
    StringLocalization.english: 'English',
    StringLocalization.hindi: 'हिन्दी',
    StringLocalization.french: 'French',
    StringLocalization.spanish: 'Spanish',

    StringLocalization.selectLanguage:'भाषा का चयन करें',
    StringLocalization.ppgNoChartDataAvailable : "कोई चार्ट डेटा उपलब्ध नहीं है.",
    StringLocalization.enterTitle : "शीर्षक दर्ज करें",
    StringLocalization.kSearchMailHint: 'मेल खोजें',
    StringLocalization.kInbox: 'इनबॉक्स',
    StringLocalization.kDrafts: 'ड्राफ्ट',
    StringLocalization.kTrash: 'कचरा',
    StringLocalization.kSent: 'भेज दिया',
    StringLocalization.appReminders: 'आवेदन अनुस्मारक',
    StringLocalization.reminders: 'अनुस्मारक',
    StringLocalization.addReminders: 'अनुस्मारक जोड़ें',
    StringLocalization.updateReminders: 'अनुस्मारक बदले',
    StringLocalization.call:'Call',
    StringLocalization.message:'Message',
    StringLocalization.qq:'QQ',
    StringLocalization.weChat:'WeChat',
    StringLocalization.linkedIn:'LinkedIn',
    StringLocalization.skype:'Skype',
    StringLocalization.facebookMessenger:'Facebook Messanger',
    StringLocalization.twitter:'Twitter',
    StringLocalization.whatsApp:'WhatsApp',
    StringLocalization.viber:'Viber',
    StringLocalization.line:'Line',
    StringLocalization.kOutBox: 'आउटबॉक्स',

    StringLocalization.startTime:"प्रारम्भ का समय",
    StringLocalization.endTime:"समाप्त का समय",
    StringLocalization.intervalTime:"अंतराल समय",
    StringLocalization.repeat:"दोहराना",
    StringLocalization.description:"विवरण",
    StringLocalization.sun:"र",
    StringLocalization.mon:"सो",
    StringLocalization.tue:"मं",
    StringLocalization.wed:"बू",
    StringLocalization.thu:"गु",
    StringLocalization.fri:"शु",
    StringLocalization.sat:"श",
    StringLocalization.selectImage:"छवि चुने",
    StringLocalization.notification:"अधिसूचना",
    StringLocalization.waterReminderTitle:"जलयोजन",
    StringLocalization.dontForgetToDrinkWater:"पानी पीना मत भूलना",
    StringLocalization.sedentaryReminderTitle:"गतिहीन",
    StringLocalization.sedentaryDesc:"यह खड़े होने का समय है।",
    StringLocalization.medicineReminderTitle:"दवाई",
    StringLocalization.medicineDesc:"अपनी दवा ले लो।",
    StringLocalization.synchronization: "से सिंक्रोनाइज़ेशन",

    StringLocalization.leadOff: 'लीड ऑफ',
    StringLocalization.leadDesc: 'कंगन पर अपनी उंगली ले जाएं।',
    StringLocalization.poorConductive: 'पुअर कंडक्टिव',
    StringLocalization.poorConductiveDesc: 'यह सेंसर के संपर्क में पानी का परीक्षण करने के लिए अनुशंसित है।',
    StringLocalization.goodSignal: 'गुड सिंगल',
    StringLocalization.readyForMeasurement: 'मापन के लिए तैयार',
    StringLocalization.measurementInProgress: 'माप प्रगति पर है।',
    StringLocalization.holdHand: '1) अभी भी अपना हाथ पकड़ो।',
    StringLocalization.braceletSung: '2) ब्रेसलेट स्नग होना चाहिए।',
    StringLocalization.putYourFinger: '3) कृपया कंगन के तल पर अपने विपरीत हाथ की \ Nindex उंगली रखें।',
    StringLocalization.recommodateMoisten: '4) यह ब्रेसलेट संपर्क के क्षेत्र में आपकी त्वचा को नमी देने की सिफारिश की गई है।',
    StringLocalization.doNotAskAgain: "मुझसे दोबारा मत पूछो",
    StringLocalization.diet: "आहार",
    StringLocalization.medicine: "चिकित्सा",
    StringLocalization.corona: "COVID-19",
    StringLocalization.smoking: "धूम्रपान",
    StringLocalization.alcohol: "अल्कोहल",
    StringLocalization.glucosepatch: 'ग्लूकोज पैच',
    StringLocalization.glucosepatchlocation: 'ग्लूकोज पैच स्थान',

    StringLocalization.allowance: "भत्ता",
    StringLocalization.search: "खोज",
    StringLocalization.more: "अधिक",
    StringLocalization.MMOLPerLiter: "mmol / L",
    StringLocalization.MMGL: "mg / dL",
    StringLocalization.measurementResult: "मापन परिणाम",
    StringLocalization.measurementData: "आपका रक्तचाप अनुमान है:",
    StringLocalization.estimating: "अनुमान",
    StringLocalization.contacts : "संपर्क",
    StringLocalization.delete : "हटाएं",
    StringLocalization.contactDeleted : "संपर्क हटा दिया गया",
    StringLocalization.noContactFound : "कोई संपर्क नहीं मिला !!!",
    StringLocalization.invitations : "निमंत्रण",
    StringLocalization.searchContact : "संपर्क खोजें",
    StringLocalization.noPendingInvitations : "कोई लंबित आमंत्रण नहीं" ,
    StringLocalization.noPendingInvitationToSearchFrom : "खोज करने के लिए कोई लंबित निमंत्रण नहीं है",
    StringLocalization.addContacts : "संपर्क जोड़ें",
    StringLocalization.invitedSucessfully : "सफलतापूर्वक आमंत्रित किया गया",
    StringLocalization.invitationFailed : "निमंत्रण विफल ",
    StringLocalization.searchNameOfUser : "उपयोगकर्ता का नाम खोजें",
    StringLocalization.nothingToShow : "दिखाने के लिए कुछ भी नहीं",
    StringLocalization.pageDeleted : "पृष्ठ हटा दिया गया",
    StringLocalization.pageAdded : "पेज जोड़ा गया",
    StringLocalization.youCanNotAddMorePages : "आप अधिक पृष्ठ नहीं जोड़ सकते",
    StringLocalization.addPage : "पृष्ठ जोड़ें",
    StringLocalization.deleteCurrentPage : "वर्तमान पृष्ठ हटाएं",
    StringLocalization.editTitleOfpage : "पृष्ठ का शीर्षक संपादित करें",
    StringLocalization.editTitle : "शीर्षक संपादित करें",
    StringLocalization.compose: "लिखें",
    StringLocalization.to: "टू",
    StringLocalization.cc: "Cc",
    StringLocalization.subject: "विषय",
    StringLocalization.body: "बॉडी",
    StringLocalization.enterAllFields: "सभी फ़ील्ड दर्ज करें",
    StringLocalization.pleaseEnterToSubject: "कृपया एक संपर्क चुनें और विषय दर्ज करें",
    StringLocalization.addToDrafts: "ड्राफ्ट में जोड़ें",
    StringLocalization.draftConfirmation: "ओके क्लिक करके आप ड्राफ्ट में मेल सेव करने की पुष्टि कर रहे हैं,",
    StringLocalization.messageSentSuccessfully: "संदेश सफलतापूर्वक भेजा गया",
    StringLocalization.messageNotSent: "संदेश भेजा नहीं गया",
    StringLocalization.untrash: "पुनर्स्थापित करें",
    StringLocalization.emailDeletedSuccessfully: "ईमेल सफलतापूर्वक हटा दिया गया",
    StringLocalization.selectAll: "सभी का चयन करें",
    StringLocalization.emailRestoredSuccessfully: "ईमेल सफलतापूर्वक बहाल",
    StringLocalization.detail: "विवरण",
    StringLocalization.from: "से",
    StringLocalization.reply: "उत्तर",
    StringLocalization.replyAll: "सभी का जवाब दें",
    StringLocalization.forward: "फॉरवर्ड",
    StringLocalization.requested : "अनुरोध किया गया है",
    StringLocalization.helpPageUrl : "asset/help.html",
    StringLocalization.healthKit : "स्वास्थ्य किट",
    StringLocalization.alarm : "अलार्म",
    StringLocalization.addAlarm: "अलार्म जोड़ें",
    StringLocalization.selectDays: "दिनों का चयन करें",
    StringLocalization.alarmLabel: "अलार्म लेबल",
    StringLocalization.selectTime : "समय का चयन करें",
    StringLocalization.addNameForBluetoothDevice: "इस उपकरण का नाम बताइए",
    StringLocalization.hideFromList : "डिवाइस को सूची से छिपाएं",
    StringLocalization.showAll : "सब दिखाओ",
    StringLocalization.hide : "छिपाना",
    StringLocalization.allSleep : "कुल नींद",
    StringLocalization.deepSleep : "हलकी नींद",
    StringLocalization.fetchAndNext: 'डेटा प्राप्त करें और आगे बढ़ें',
    StringLocalization.autoLoad: "Auto Load",
    StringLocalization.autoTagging: "Auto Tagging",
    StringLocalization.termsAndConditionPageUrl: "asset/terms_and_condition.html",

    StringLocalization.systolic: "Sys",
    StringLocalization.diastolic: "Dia",
    StringLocalization.goal: "Goal",
    StringLocalization.awake: "Awake",//todo remaining
    StringLocalization.chooseYourCaloriesTarget: "Choose your calories target",//todo remaining
    StringLocalization.caloriesSuggestion: "Suggest adult woman 1600 ~ 2400 calories a day and adult man 2000 ~ 3000 a day.",//todo remaining
    StringLocalization.caloriesTarget: "Calories Target: ",//todo remaining
    StringLocalization.chooseYourDistanceTarget: "Choose your distance target",//todo remaining
    StringLocalization.distanceTarget: "Distance Target: ",//todo remaining
    StringLocalization.distanceSuggestion: "Suggest 5 ~ 7 km a day",//todo remaining
    StringLocalization.normal: "Normal",//todo remaining
    StringLocalization.resting: "Resting",//todo remaining
    StringLocalization.resting: "Walking",//todo remaining
    StringLocalization.exercising: "Exercising",//todo remaining
    StringLocalization.slow: "Slow",//todo remaining
    StringLocalization.fast: "Fast",//todo remaining
    StringLocalization.whatStateAreYouMeasuringIn: "What state are you measuring in?",//todo remaining
    StringLocalization.maxEffort: "Max Effort",//todo remaining
    StringLocalization.hardCoreTraining: "Hardcore Training",//todo remaining
    StringLocalization.enduranceTraining: "Endurance Training",//todo remaining
    StringLocalization.fatBurning: "Fat Burning",//todo remaining
    StringLocalization.normalization: "Normalization",//todo remaining
    StringLocalization.oscillometric: "Oscillometric AI Verification",//todo remaining
    StringLocalization.heartRateShortForm: "HR",//todo remaining
    StringLocalization.wrongData: "Measurement Stopped!",//todo remaining
    StringLocalization.wrongDataDescription: "Measurement data is incorrect, do you want to restart measurement?",//todo remaining
    StringLocalization.restart: "Restart",//todo remaining
    StringLocalization.MMOL: "mmol/l",
    StringLocalization.MGDL: "mg/dl",
    StringLocalization.fahrenheit: "Fahrenheit",
    StringLocalization.glass: "Glass",
    StringLocalization.running: "Running",
    StringLocalization.hiking: "Hiking",
    StringLocalization.biking: "Biking",
    StringLocalization.easy: "Easy",
    StringLocalization.moderate: "Moderate",
    StringLocalization.brightness : "Brightness",
    StringLocalization.Low : "Low",
    StringLocalization.Medium : "Medium",
    StringLocalization.High : "High",
    StringLocalization.homeScreenItems : "Home Screen Items",
    StringLocalization.bloodPressure: 'Blood Pressure',
    StringLocalization.bloodOxygen: 'Blood Oxygen',
    StringLocalization.activeCalorieBurn: 'सक्रिय कैलोरी बर्न',
    StringLocalization.restingCalorieBurn: 'आराम करने वाली कैलोरी बर्न',
    StringLocalization.gmail : "gmail",
    StringLocalization.instagram : "instagram",
    StringLocalization.snapchat : "snapchat",
    StringLocalization.facebook : "facebook",
    StringLocalization.weibo : "weibo",
    StringLocalization.clickAgain : "press back again to exit",
    StringLocalization.surveyList : "Survey List",
    StringLocalization.addSurvey : "Add Survey",
    StringLocalization.addQuestion : "Add Question",
    StringLocalization.backText : "Back",
    StringLocalization.kSend : "Send",
    StringLocalization.interpolation : "Interpolation",
    StringLocalization.cameraMeasurement : "Camera Measurement",
    StringLocalization.setUnit: 'Unit Settings',
    StringLocalization.confirmationText : "क्या आप जारी रखना चाहते हैं?",
    StringLocalization.celsiusShort:"°C",
    StringLocalization.fahrenheitShort:"°F",
    StringLocalization.unitSetSuccess:"Unit set successfully",
    StringLocalization.voiceConfiguration: 'Voice Configuration',
    StringLocalization.noConnectionMessage: 'Device Not Connected. Please connect a device.',
    StringLocalization.hgSyncedSuccessfully: 'HG वॉच सफलतापूर्वक सिंक हो गई है',
  };
}