name: charts_flutter
version: 0.11.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts
# commit: 30477090290b348ed3101bc13017aae465f59017

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
#  charts_common: 0.11.0
  charts_common:
    path: ../charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: any
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.0.17
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  test: ^1.20.1

dependency_overrides:
  test_api: ^0.4.9